/**
 * @generated
 * @file SectionDefaultTemplate (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import BlockContainer from "../webflow_modules/Layout/components/BlockContainer";
import Section from "../webflow_modules/Layout/components/Section";

/**
 * Props for {@link SectionDefaultTemplate}
 */
export type SectionDefaultTemplateProps = {
  slot?: React.ReactNode;
};

/**
 * SectionDefaultTemplate
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function SectionDefaultTemplate({ slot }: SectionDefaultTemplateProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section-v7"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"container-v7"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          {slot}
        </BlockContainer>
      </Section>
    </div>
  );
}
