/**
 * @generated
 * @file SectionWithBgV7 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import BlockContainer from "../webflow_modules/Layout/components/BlockContainer";
import Section from "../webflow_modules/Layout/components/Section";

/**
 * Props for {@link SectionWithBgV7}
 */
export type SectionWithBgV7Props = {
  slot?: React.ReactNode;
};

/**
 * SectionWithBgV7
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function SectionWithBgV7({ slot }: SectionWithBgV7Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section-with-bg bg-black"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"container-v7"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          {slot}
        </BlockContainer>
      </Section>
    </div>
  );
}
