/**
 * @generated
 * @file SectionHero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import BackgroundVideoWrapper from "../webflow_modules/BackgroundVideo/components/BackgroundVideoWrapper";
import Block from "../webflow_modules/Basic/components/Block";
import HFlex from "../webflow_modules/Layout/components/HFlex";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";
import Section from "../webflow_modules/Layout/components/Section";
import VFlex from "../webflow_modules/Layout/components/VFlex";
import { ButtonFullV7 } from "../ButtonFullV7";
import { ButtonScroll } from "../v7Buttons/ButtonScroll";
import { CardImageAndText } from "../v7SmallComponents/CardImageAndText";
import { Copy } from "../v7Typography/Copy";
import { Heading } from "../v7Typography/Heading";
import { LabelHeroStars } from "../v7SmallComponents/LabelHeroStars";
import { LabelHeroText } from "../v7SmallComponents/LabelHeroText";

/**
 * Props for {@link SectionHero}
 */
export type SectionHeroProps = {
  announcementsImage?: string;
  announcementsLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  announcementsVariant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  announcementsVisibility?: boolean;
  breadcrumbsLink1?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  breadcrumbsLink2?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  breadcrumbsLink3?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  breadcrumbsSlash1Visibility?: boolean;
  breadcrumbsSlash2Visibility?: boolean;
  breadcrumbsText1?: React.ReactNode;
  breadcrumbsText2?: React.ReactNode;
  breadcrumbsText3?: React.ReactNode;
  breadcrumbsVisibility?: boolean;
  copy3Variant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  headingCtaLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  headingCtaText?: React.ReactNode;
  headingCtaVariant?:
    | "Base"
    | "orange-bg/white-text"
    | "blue-border/blue-text/max:full-width"
    | "white-border/white-text/max:full-width";
  headingCtaVisibility?: boolean;
  headingLabelStarsLabelText?: React.ReactNode;
  headingLabelStarsLabelVisibility?: boolean;
  headingLabelTextLabelText?: React.ReactNode;
  headingLabelTextLabelVisibility?: boolean;
  headingTitle?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  headingTitleTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  headingVariant?:
    | "h1 (84:43/92:51)"
    | "h1 (84:40/92:48)"
    | "h2"
    | "Base (DONOT RESTYLE)";
  parntnersBannerImage1?: string;
  parntnersBannerImage2?: string;
  parntnersBannerImage3?: string;
  parntnersBannerImage4?: string;
  parntnersBannerImage5?: string;
  parntnersBannerImage6?: string;
  parntnersBannerImage7?: string;
  parntnersBannerText?: React.ReactNode;
  parntnersBannerVariant?: React.ReactNode;
  scrollButtonLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  subHeadingText?: React.ReactNode;
  subHeadingVariant?: React.ReactNode;
};

/**
 * SectionHero
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function SectionHero({
  announcementsImage = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e13affdf278a4354222055_announcement-1.webp",

  announcementsLink = {
    href: "#",
    target: "_blank",
  },

  announcementsVariant = "Inter/700/16/28/white",
  announcementsVisibility = true,

  breadcrumbsLink1 = {
    href: "/",
  },

  breadcrumbsLink2 = {
    href: "/careers",
  },

  breadcrumbsLink3 = {
    href: "#",
  },

  breadcrumbsSlash1Visibility = true,
  breadcrumbsSlash2Visibility = true,
  breadcrumbsText1 = "Home",
  breadcrumbsText2 = "Careers",
  breadcrumbsText3 = "Frequently Asked Questions",
  breadcrumbsVisibility = true,
  copy3Variant = "golos/700/18/28/white",

  headingCtaLink = {
    href: "#",
    target: "_blank",
  },

  headingCtaText = "Text",
  headingCtaVariant = "Base",
  headingCtaVisibility = true,
  headingLabelStarsLabelText = "4.9",
  headingLabelStarsLabelVisibility = true,
  headingLabelTextLabelText = "ENTERPRISE DEVELOPMENT",
  headingLabelTextLabelVisibility = true,
  headingTitle = "golos/700/24:20/36:28/white",
  headingTitleTag = "h1",
  headingVariant = "h1 (84:43/92:51)",
  parntnersBannerImage1 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e0eee8b834833e361f2248_puma-white.svg",
  parntnersBannerImage2 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e0eee8b73bab8bf8301515_michigan-white.svg",
  parntnersBannerImage3 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e0eee9d7983fd9c9360e3f_the-newyork-times-white.svg",
  parntnersBannerImage4 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e9f84abdb5b8935897671b_75800b174173b125f32594eb13ceab1d_boy-scouts-of-america.png",
  parntnersBannerImage5 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e0eee8cb825282408df2ce_adobe-white.svg",
  parntnersBannerImage6 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e9f6923f4b882653aa2d67_acer.png",
  parntnersBannerImage7 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69e0eee89302c7a1be86b802_samsung-white.svg",
  parntnersBannerText = "Trusted by 600+ leading brands worldwide",
  parntnersBannerVariant = "AI workshops to redefine your business. See schedule!",

  scrollButtonLink = {
    href: "#proud",
  },

  subHeadingText = "your own enterprise system developed 2-10x faster at up to 90% lower cost",
  subHeadingVariant = "",
}: SectionHeroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"c-section-hero--section"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BackgroundVideoWrapper
          autoPlay={true}
          className={"bg-video-home-hero"}
          loop={true}
          posterImage={
            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F69ee439628f0e2f7f45c7046_home-hero-bg_poster.0000000.jpg"
          }
          sources={[
            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F69ee439628f0e2f7f45c7046_home-hero-bg_webm.webm",
            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F69ee439628f0e2f7f45c7046_home-hero-bg_mp4.mp4",
          ]}
          tag={"div"}
        />
        <Block className={"c-section-hero--main-flexbox"} tag={"div"}>
          <Block className={"container-v7 _w-full"} tag={"div"}>
            {breadcrumbsVisibility ? (
              <Block className={"breadcrumbs-container v7"} tag={"div"}>
                <Block className={"breadcrumbs-wrapper v7"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"dark-layout link"}
                    options={breadcrumbsLink1}
                  >
                    <Block className={"text-block-474 v7"} tag={"div"}>
                      {breadcrumbsText1}
                    </Block>
                  </Link>
                  {breadcrumbsSlash1Visibility ? (
                    <Block className={"dark-layout roboto"} tag={"div"}>
                      {"/"}
                    </Block>
                  ) : null}
                  <Link
                    block={"inline"}
                    button={false}
                    className={"dark-layout link second"}
                    options={breadcrumbsLink2}
                  >
                    <Block className={"text-block-475 second v7"} tag={"div"}>
                      {breadcrumbsText2}
                    </Block>
                  </Link>
                  {breadcrumbsSlash2Visibility ? (
                    <Block className={"dark-layout roboto"} tag={"div"}>
                      {"/"}
                    </Block>
                  ) : null}
                  <Link
                    block={"inline"}
                    button={false}
                    className={"dark-layout link active-link third v7"}
                    options={breadcrumbsLink3}
                  >
                    <Block className={"text-block-476"} tag={"div"}>
                      {breadcrumbsText3}
                    </Block>
                  </Link>
                </Block>
              </Block>
            ) : null}
          </Block>
          <Block className={"container-v7 _w-full"} tag={"div"}>
            <VFlex className={"c-section-hero--text-container"} tag={"div"}>
              <LabelHeroText
                copyText={headingLabelTextLabelText}
                copyVariant={"Inter/700/16/28/white"}
                visibility={headingLabelTextLabelVisibility}
              />
              <LabelHeroStars
                copyText={headingLabelStarsLabelText}
                visibility={headingLabelStarsLabelVisibility}
              />
              <Block className={"div-block-1941"} tag={"div"}>
                <Heading
                  title={subHeadingVariant}
                  titleTag={headingTitleTag}
                  variant={headingVariant}
                />
                <Block className={"div-block-1943"} tag={"div"}>
                  <Copy text={subHeadingText} variant={headingTitle} />
                </Block>
              </Block>
              {headingCtaVisibility ? (
                <Block className={"div-block-2027"} tag={"div"}>
                  <ButtonFullV7
                    link={headingCtaLink}
                    text={headingCtaText}
                    variant={headingCtaVariant}
                  />
                </Block>
              ) : null}
            </VFlex>
          </Block>
          <VFlex className={"flex-block-73"} tag={"div"}>
            <Block className={"container-v7 _w-full"} tag={"div"}>
              <HFlex className={"flex-block-79"} tag={"div"}>
                <ButtonScroll link={scrollButtonLink} />
                {announcementsVisibility ? (
                  <Block className={"announcement-container"} tag={"div"}>
                    <Block className={"div-block-1945"} tag={"div"} />
                    <CardImageAndText
                      copyText={parntnersBannerVariant}
                      copyVariant={announcementsVariant}
                      image={announcementsImage}
                      link={announcementsLink}
                    />
                  </Block>
                ) : null}
              </HFlex>
            </Block>
            <Block className={"div-block-1964"} tag={"div"}>
              <Block className={"c-banner-brands-container"} tag={"div"}>
                <Block className={"container-v7"} tag={"div"}>
                  <HFlex className={"flex-block-74"} tag={"div"}>
                    <Block className={"div-block-1942"} tag={"div"}>
                      <Copy text={parntnersBannerText} variant={copy3Variant} />
                    </Block>
                    <Image
                      alt={""}
                      className={"image-4521"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage1}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4522"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage2}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4523"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage3}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4547"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage4}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4548"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage5}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4549"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage6}
                      width={"auto"}
                    />
                    <Image
                      alt={""}
                      className={"image-4550"}
                      height={"auto"}
                      loading={"lazy"}
                      src={parntnersBannerImage7}
                      width={"auto"}
                    />
                  </HFlex>
                </Block>
              </Block>
            </Block>
          </VFlex>
        </Block>
      </Section>
    </div>
  );
}
