/**
 * @generated
 * @file BannerRating (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HFlex from "../webflow_modules/Layout/components/HFlex";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";
import VFlex from "../webflow_modules/Layout/components/VFlex";

/**
 * Props for {@link BannerRating}
 */
export type BannerRatingProps = {
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
};

/**
 * BannerRating
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function BannerRating({
  link = {
    href: "/customers-saying-about-strengths-of-scandiweb",
    target: "_blank",
  },

  text1 = "4.9",
  text2 = "rated by top companies",
  text3 = "Read reviews",
}: BannerRatingProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"rating-v7"} tag={"div"}>
        <Block className={"div-block-1886"} tag={"div"}>
          <Block className={"div-block-1867"} tag={"div"}>
            <Block className={"rating-number"} tag={"div"}>
              {text1}
            </Block>
          </Block>
          <VFlex className={"flex-block-70"} tag={"div"}>
            <HFlex className={"flex-block-71"} tag={"div"}>
              <HtmlEmbed
                className={"code-embed-170"}
                content={""}
                value={
                  "%3Csvg%20width%3D%2230%22%20height%3D%2230%22%20viewBox%3D%220%200%2030%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_31453_31854)%22%3E%0A%3Cpath%20d%3D%22M14.5383%201.85996C14.7091%201.44932%2015.2909%201.44932%2015.4617%201.85996L18.8503%2010.0072C18.9223%2010.1803%2019.0851%2010.2986%2019.272%2010.3135L28.0675%2011.0187C28.5109%2011.0542%2028.6906%2011.6075%2028.3529%2011.8968L21.6516%2017.6372C21.5092%2017.7592%2021.447%2017.9506%2021.4905%2018.1329L23.5378%2026.7159C23.641%2027.1485%2023.1704%2027.4905%2022.7909%2027.2586L15.2606%2022.6592C15.1006%2022.5615%2014.8994%2022.5615%2014.7394%2022.6592L7.20913%2027.2586C6.82958%2027.4905%206.35896%2027.1485%206.46215%2026.7159L8.50951%2018.1329C8.55301%2017.9506%208.49083%2017.7592%208.34843%2017.6372L1.64713%2011.8968C1.30936%2011.6075%201.48912%2011.0542%201.93245%2011.0187L10.728%2010.3135C10.9149%2010.2986%2011.0777%2010.1803%2011.1497%2010.0072L14.5383%201.85996Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_31453_31854%22%3E%0A%3Crect%20width%3D%2230%22%20height%3D%2230%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
                }
              />
              <HtmlEmbed
                className={"code-embed-170"}
                content={""}
                value={
                  "%3Csvg%20width%3D%2230%22%20height%3D%2230%22%20viewBox%3D%220%200%2030%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_31453_31854)%22%3E%0A%3Cpath%20d%3D%22M14.5383%201.85996C14.7091%201.44932%2015.2909%201.44932%2015.4617%201.85996L18.8503%2010.0072C18.9223%2010.1803%2019.0851%2010.2986%2019.272%2010.3135L28.0675%2011.0187C28.5109%2011.0542%2028.6906%2011.6075%2028.3529%2011.8968L21.6516%2017.6372C21.5092%2017.7592%2021.447%2017.9506%2021.4905%2018.1329L23.5378%2026.7159C23.641%2027.1485%2023.1704%2027.4905%2022.7909%2027.2586L15.2606%2022.6592C15.1006%2022.5615%2014.8994%2022.5615%2014.7394%2022.6592L7.20913%2027.2586C6.82958%2027.4905%206.35896%2027.1485%206.46215%2026.7159L8.50951%2018.1329C8.55301%2017.9506%208.49083%2017.7592%208.34843%2017.6372L1.64713%2011.8968C1.30936%2011.6075%201.48912%2011.0542%201.93245%2011.0187L10.728%2010.3135C10.9149%2010.2986%2011.0777%2010.1803%2011.1497%2010.0072L14.5383%201.85996Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_31453_31854%22%3E%0A%3Crect%20width%3D%2230%22%20height%3D%2230%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
                }
              />
              <HtmlEmbed
                className={"code-embed-170"}
                content={""}
                value={
                  "%3Csvg%20width%3D%2230%22%20height%3D%2230%22%20viewBox%3D%220%200%2030%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_31453_31854)%22%3E%0A%3Cpath%20d%3D%22M14.5383%201.85996C14.7091%201.44932%2015.2909%201.44932%2015.4617%201.85996L18.8503%2010.0072C18.9223%2010.1803%2019.0851%2010.2986%2019.272%2010.3135L28.0675%2011.0187C28.5109%2011.0542%2028.6906%2011.6075%2028.3529%2011.8968L21.6516%2017.6372C21.5092%2017.7592%2021.447%2017.9506%2021.4905%2018.1329L23.5378%2026.7159C23.641%2027.1485%2023.1704%2027.4905%2022.7909%2027.2586L15.2606%2022.6592C15.1006%2022.5615%2014.8994%2022.5615%2014.7394%2022.6592L7.20913%2027.2586C6.82958%2027.4905%206.35896%2027.1485%206.46215%2026.7159L8.50951%2018.1329C8.55301%2017.9506%208.49083%2017.7592%208.34843%2017.6372L1.64713%2011.8968C1.30936%2011.6075%201.48912%2011.0542%201.93245%2011.0187L10.728%2010.3135C10.9149%2010.2986%2011.0777%2010.1803%2011.1497%2010.0072L14.5383%201.85996Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_31453_31854%22%3E%0A%3Crect%20width%3D%2230%22%20height%3D%2230%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
                }
              />
              <HtmlEmbed
                className={"code-embed-170"}
                content={""}
                value={
                  "%3Csvg%20width%3D%2230%22%20height%3D%2230%22%20viewBox%3D%220%200%2030%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_31453_31854)%22%3E%0A%3Cpath%20d%3D%22M14.5383%201.85996C14.7091%201.44932%2015.2909%201.44932%2015.4617%201.85996L18.8503%2010.0072C18.9223%2010.1803%2019.0851%2010.2986%2019.272%2010.3135L28.0675%2011.0187C28.5109%2011.0542%2028.6906%2011.6075%2028.3529%2011.8968L21.6516%2017.6372C21.5092%2017.7592%2021.447%2017.9506%2021.4905%2018.1329L23.5378%2026.7159C23.641%2027.1485%2023.1704%2027.4905%2022.7909%2027.2586L15.2606%2022.6592C15.1006%2022.5615%2014.8994%2022.5615%2014.7394%2022.6592L7.20913%2027.2586C6.82958%2027.4905%206.35896%2027.1485%206.46215%2026.7159L8.50951%2018.1329C8.55301%2017.9506%208.49083%2017.7592%208.34843%2017.6372L1.64713%2011.8968C1.30936%2011.6075%201.48912%2011.0542%201.93245%2011.0187L10.728%2010.3135C10.9149%2010.2986%2011.0777%2010.1803%2011.1497%2010.0072L14.5383%201.85996Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_31453_31854%22%3E%0A%3Crect%20width%3D%2230%22%20height%3D%2230%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
                }
              />
              <HtmlEmbed
                className={"code-embed-170"}
                content={""}
                value={
                  "%3Csvg%20width%3D%2230%22%20height%3D%2230%22%20viewBox%3D%220%200%2030%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_31453_31854)%22%3E%0A%3Cpath%20d%3D%22M14.5383%201.85996C14.7091%201.44932%2015.2909%201.44932%2015.4617%201.85996L18.8503%2010.0072C18.9223%2010.1803%2019.0851%2010.2986%2019.272%2010.3135L28.0675%2011.0187C28.5109%2011.0542%2028.6906%2011.6075%2028.3529%2011.8968L21.6516%2017.6372C21.5092%2017.7592%2021.447%2017.9506%2021.4905%2018.1329L23.5378%2026.7159C23.641%2027.1485%2023.1704%2027.4905%2022.7909%2027.2586L15.2606%2022.6592C15.1006%2022.5615%2014.8994%2022.5615%2014.7394%2022.6592L7.20913%2027.2586C6.82958%2027.4905%206.35896%2027.1485%206.46215%2026.7159L8.50951%2018.1329C8.55301%2017.9506%208.49083%2017.7592%208.34843%2017.6372L1.64713%2011.8968C1.30936%2011.6075%201.48912%2011.0542%201.93245%2011.0187L10.728%2010.3135C10.9149%2010.2986%2011.0777%2010.1803%2011.1497%2010.0072L14.5383%201.85996Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_31453_31854%22%3E%0A%3Crect%20width%3D%2230%22%20height%3D%2230%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
                }
              />
            </HFlex>
            <Block className={"text-block-537"} tag={"div"}>
              {text2}
            </Block>
          </VFlex>
        </Block>
        <Link
          block={"inline"}
          button={false}
          className={"button-full-green-v7 blue stretch"}
          options={link}
        >
          <Block tag={"div"}>{text3}</Block>
          <HtmlEmbed
            content={""}
            value={
              "%3Cstyle%3E%0A%20%20.button-full-green-v7%3Ahover%20%7B%0A%20%20%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E"
            }
          />
        </Link>
      </Block>
    </div>
  );
}
