/**
 * @generated
 * @file BreadcrumbsV7 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";
import { applyPredicate } from "../webflow_modules/Conditions/helpers/applyPredicate";
import { textIsSet } from "../webflow_modules/ListOfElements/helpers/textIsSet";

/**
 * Props for {@link BreadcrumbsV7}
 */
export type BreadcrumbsV7Props = {
  /** added on pages that have a darker first section*/
  darkLayout?: boolean;
  /** first breadcrumb link*/
  level1Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** first breadcrumb value*/
  level1Text?: React.ReactNode;
  /** second breadcrumb link*/
  level2Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** second breadcrumb value*/
  level2Text?: React.ReactNode;
  /** third breadcrumb link*/
  level3Link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  /** third breadcrumb value*/
  level3Text?: React.ReactNode;
  variant?: "Base" | "two-level";
};

/**
 * BreadcrumbsV7
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function BreadcrumbsV7({
  darkLayout = true,

  level1Link = {
    href: "/",
  },

  level1Text = "Home",

  level2Link = {
    href: "/careers",
  },

  level2Text = "Careers",

  level3Link = {
    href: "#",
  },

  level3Text = "Frequently Asked Questions",
  variant = "Base",
}: BreadcrumbsV7Props) {
  const _styleVariantMap = {
    Base: "",
    "two-level": "w-variant-84c3a620-daf8-acad-7ea2-ee0c1f5d131f",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`breadcrumbs-container v7 ${_activeStyleVariant}`}
        tag={"div"}
      >
        <Block
          className={`breadcrumbs-wrapper v7 ${_activeStyleVariant}`}
          tag={"div"}
        >
          <Link
            block={"inline"}
            button={false}
            className={`dark-layout link ${_activeStyleVariant}`}
            options={level1Link}
          >
            <Block
              className={`text-block-474 ${_activeStyleVariant}`}
              tag={"div"}
            >
              {level1Text}
            </Block>
          </Link>
          <Block
            className={`dark-layout roboto ${_activeStyleVariant}`}
            tag={"div"}
          >
            {"/"}
          </Block>
          <Link
            block={"inline"}
            button={false}
            className={`dark-layout link second ${_activeStyleVariant}`}
            options={level2Link}
          >
            <Block
              className={`text-block-475 second ${_activeStyleVariant}`}
              tag={"div"}
            >
              {level2Text}
            </Block>
          </Link>
          {applyPredicate(level3Text)(textIsSet) ? (
            <Block
              className={`dark-layout roboto ${_activeStyleVariant}`}
              tag={"div"}
            >
              {"/"}
            </Block>
          ) : null}
          <Link
            block={"inline"}
            button={false}
            className={`dark-layout link active-link third ${_activeStyleVariant}`}
            options={level3Link}
          >
            <Block
              className={`text-block-476 ${_activeStyleVariant}`}
              tag={"div"}
            >
              {level3Text}
            </Block>
          </Link>
        </Block>
      </Block>
    </div>
  );
}
