/**
 * @generated
 * @file CallToAction (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading2 from "../webflow_modules/Basic/components/Heading";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";
import Span from "../webflow_modules/Basic/components/Span";
import VFlex from "../webflow_modules/Layout/components/VFlex";
import { Copy } from "../v7Typography/Copy";
import { Heading } from "../v7Typography/Heading";

/**
 * Props for {@link CallToAction}
 */
export type CallToActionProps = {
  copyText?: React.ReactNode;
  copyVariant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  cta1Image?: string;
  cta1Link1?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  cta1Text1?: React.ReactNode;
  cta1Visibility?: boolean;
  cta2Link2?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  cta2Text2?: React.ReactNode;
  cta2Visibility?: boolean;
  cta3Link3?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  cta3Text3?: React.ReactNode;
  cta3Visibility?: boolean;
  headingCareerVisibility?: boolean;
  headingHeadingConsultationVisibility?: boolean;
  headingTitle?: React.ReactNode;
  headingTitleTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  headingVariant?:
    | "h1 (84:43/92:51)"
    | "h1 (84:40/92:48)"
    | "h2"
    | "Base (DONOT RESTYLE)";
};

/**
 * CallToAction
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function CallToAction({
  copyText = "Planning a new store, expanding to global markets, or looking to adopt latest technology? Reach out to us, and let's make it happen.",
  copyVariant = "Inter/400/16/28/grey",
  cta1Image = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6835cf6db25494bcc425bb4c_image%20432.png",

  cta1Link1 = {
    href: "https://scandiweb.com/contact",
  },

  cta1Text1 = "Book a consultation",
  cta1Visibility = true,

  cta2Link2 = {
    href: "https://scandiweb.com/services",
    target: "_blank",
  },

  cta2Text2 = "All services",
  cta2Visibility = true,

  cta3Link3 = {
    href: "/careers",
  },

  cta3Text3 = "Explore careers",
  cta3Visibility = true,
  headingCareerVisibility = true,
  headingHeadingConsultationVisibility = true,
  headingTitle = " ",
  headingTitleTag = "h1",
  headingVariant = "h2",
}: CallToActionProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"div-block-1955"} tag={"div"}>
        <Block className={"container-v7"} tag={"div"}>
          <VFlex className={"flex-block-83"} tag={"div"}>
            <VFlex className={"flex-block-84"} tag={"div"}>
              {headingCareerVisibility ? (
                <Block tag={"div"}>
                  <Heading
                    title={
                      <>
                        <Span className={"text-span-280"}>{"Let's do"}</Span>{" "}
                        <Span className={"text-span-279"}>
                          {"meaningful work together"}
                        </Span>
                      </>
                    }
                    titleTag={"h2"}
                    variant={"h2"}
                  />
                </Block>
              ) : null}
              {headingHeadingConsultationVisibility ? (
                <Block tag={"div"}>
                  <Heading2 className={"c-heading h2-5"} tag={"h2"}>
                    <Span className={"text-span-277"}>{"‍"}</Span>{" "}
                    <Span className={"text-span-279"}>{"Let's build "}</Span>
                    <Span className={"text-span-285"}>
                      {"something great together"}
                    </Span>
                    <Span className={"text-span-279"}> </Span>
                  </Heading2>
                </Block>
              ) : null}
              <Copy text={copyText} variant={copyVariant} />
            </VFlex>
            <Block
              className={
                "div-block-1823 hide-on-mobile-13 reorder-consultation-as-1st-18"
              }
              tag={"div"}
            >
              {cta1Visibility ? (
                <Link
                  block={"inline"}
                  button={false}
                  className={
                    "link-block-71 hide-on-mobile-14 reorder-consultation-as-1st-19"
                  }
                  options={cta1Link1}
                >
                  <Image
                    alt={""}
                    className={
                      "hide-on-mobile persons hide-on-mobile-15 reorder-consultation-as-1st-20"
                    }
                    height={"auto"}
                    loading={"lazy"}
                    src={cta1Image}
                    width={"auto"}
                  />
                  <Block
                    className={
                      "text-block-515 hide-on-mobile-16 reorder-consultation-as-1st-21"
                    }
                    tag={"div"}
                  >
                    {cta1Text1}
                  </Block>
                </Link>
              ) : null}
              {cta2Visibility ? (
                <Link
                  block={""}
                  button={true}
                  className={"cta_white stroke reorder-consultation-as-1st-22"}
                  options={cta2Link2}
                >
                  {cta2Text2}
                </Link>
              ) : null}
              {cta3Visibility ? (
                <Link
                  block={""}
                  button={true}
                  className={
                    "button-full-green-v7 reorder-consultation-as-1st-23"
                  }
                  options={cta3Link3}
                >
                  {cta3Text3}
                </Link>
              ) : null}
            </Block>
          </VFlex>
        </Block>
      </Block>
    </div>
  );
}
