/**
 * @generated
 * @file ExpandableShortService (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HFlex from "../webflow_modules/Layout/components/HFlex";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";
import { Copy } from "../v7Typography/Copy";

/**
 * Props for {@link ExpandableShortService}
 */
export type ExpandableShortServiceProps = {
  containerCustomAttributes?: Record<string, unknown>;
  copy2CopyVisibility?: boolean;
  copy2Text?: React.ReactNode;
  copy2Variant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  copyText?: React.ReactNode;
  copyVariant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
};

/**
 * ExpandableShortService
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ExpandableShortService({
  containerCustomAttributes = {},
  copy2CopyVisibility = true,
  copy2Text = "Copy",
  copy2Variant = "Inter/400/16/28/black",
  copyText = "Heading",
  copyVariant = "golos/700/24:20/36:28/black",

  link = {
    href: "#",
    target: "_blank",
  },
}: ExpandableShortServiceProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"expandable-short-service--container"}
        data-onclick-class={"jsclose"}
        data-onclick-group={"small-services"}
        data-onclick-group-lock={""}
        data-onclick-group-open-first={""}
        options={link}
        {...containerCustomAttributes}
      >
        <HFlex className={"flex-block-113"} tag={"div"}>
          <Copy text={copyText} variant={copyVariant} />
          <HtmlEmbed
            className={"code-embed-185"}
            content={""}
            value={
              "%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cg%20clip-path%3D%22url(%23clip0_32238_47854)%22%3E%0A%3Cpath%20d%3D%22M16.5576%206.0188L5.99933%206.0188V4L19.9947%204L19.9948%2018H17.9993L17.976%207.45544L5.43141%2020L4.00391%2018.5725L16.5576%206.0188Z%22%20fill%3D%22%2310132C%22%2F%3E%0A%3C%2Fg%3E%0A%3Cdefs%3E%0A%3CclipPath%20id%3D%22clip0_32238_47854%22%3E%0A%3Crect%20width%3D%2224%22%20height%3D%2224%22%20fill%3D%22white%22%2F%3E%0A%3C%2FclipPath%3E%0A%3C%2Fdefs%3E%0A%3C%2Fsvg%3E"
            }
          />
        </HFlex>
        {copy2CopyVisibility ? (
          <Block
            className={"expandable-short-service--copy-container"}
            data-onclick-child={""}
            tag={"div"}
          >
            <Copy text={copy2Text} variant={copy2Variant} />
          </Block>
        ) : null}
      </Link>
    </div>
  );
}
