/**
 * @generated
 * @file ShowMoreButton (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import { Copy } from "../v7Typography/Copy";

/**
 * Props for {@link ShowMoreButton}
 */
export type ShowMoreButtonProps = {
  copyText?: React.ReactNode;
  copyVariant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
};

/**
 * ShowMoreButton
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ShowMoreButton({
  copyText = "Show 8 more",
  copyVariant = "Inter/700/16/28/blue",
}: ShowMoreButtonProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"div-block-2042"}
        data-show-more={""}
        data-show-more-group={"small-services"}
        data-show-more-hide-class={"js-hide"}
        tag={"div"}
      >
        <Copy text={copyText} variant={copyVariant} />
        <HtmlEmbed
          className={"code-embed-186"}
          content={""}
          value={
            "%3Csvg%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M9%207H14V9H9V14H7V9H2V7H7V2H9V7Z%22%20fill%3D%22%233F4AAF%22%2F%3E%0A%3C%2Fsvg%3E"
          }
        />
      </Block>
    </div>
  );
}
