/**
 * @generated
 * @file Copy (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link Copy}
 */
export type CopyProps = {
  text?: React.ReactNode;
  variant?:
    | "golos/700/74:52/n:60/black"
    | "golos/700/56:36/68:44/orange"
    | "golos/700/36:24/44:32/inherit-color"
    | "golos/700/36:24/44:32/white"
    | "golos/700/36:24/44:32/green"
    | "golos/700/36:24/44:32/faded-grey>white"
    | "golos/700/36:24/44:32/black"
    | "golos/700/24/36/black"
    | "golos/700/24:20/36:28/white"
    | "golos/700/24:20/36:28/black"
    | "golos/700/24:16/36:28/white"
    | "golos/700/20/28/white"
    | "golos/700/18/28/white"
    | "Inter/700/24/36/white"
    | "Inter/700/24/36/black"
    | "Inter/700/24:16/36:28/white"
    | "Inter/700/16/28/white"
    | "Inter/700/16/28/blue"
    | "Inter/700/16/28/black"
    | "Inter/700/14/20/blue"
    | "Inter/700/14/20/black"
    | "Inter/700/9/9/black"
    | "Inter/400/24/36/white"
    | "Inter/400/16/28/white"
    | "Inter/400/16/28/grey"
    | "Inter/400/16/28/black"
    | "Inter/400/14/20/white"
    | "Inter/400/14/20/light-grey"
    | "Inter/400/14/20/dark-grey"
    | "Inter/400/14:16/20:28/black"
    | "Inter/400/12/16/dark-grey"
    | "Roboto/700/16/24/green"
    | "Roboto/700/20/28/white"
    | "Base (DONOT RESTYLE THIS ONE)";
};

/**
 * Copy
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function Copy({
  text = "Copy.",
  variant = "Base (DONOT RESTYLE THIS ONE)",
}: CopyProps) {
  const _styleVariantMap = {
    "golos/700/74:52/n:60/black":
      "w-variant-86e1a27f-b99b-a6e5-680b-6f83d8377d1d",
    "golos/700/56:36/68:44/orange":
      "w-variant-49f2d9e0-f7d4-ec99-9e4b-ed4988249033",
    "golos/700/36:24/44:32/inherit-color":
      "w-variant-dba9742e-ab70-0cd3-c53c-bc1e581fe4c0",
    "golos/700/36:24/44:32/white":
      "w-variant-3ac7fb51-3678-520f-98a7-e65a4e6ec2a8",
    "golos/700/36:24/44:32/green":
      "w-variant-c39751e7-8255-4b8a-aa74-acc15f2494e7",
    "golos/700/36:24/44:32/faded-grey>white":
      "w-variant-5ad97f50-9e6d-0cd6-3e74-cf192d1f4184",
    "golos/700/36:24/44:32/black":
      "w-variant-0980aaa7-42d3-f11f-8d48-55028de8d4fb",
    "golos/700/24/36/black": "w-variant-48f0ca02-7e7a-c63f-adbe-b1d05c688d0a",
    "golos/700/24:20/36:28/white":
      "w-variant-30224548-8d95-b13f-7e05-f47efa41b5b5",
    "golos/700/24:20/36:28/black":
      "w-variant-604a1384-64fc-e9b9-ed71-04f335dade40",
    "golos/700/24:16/36:28/white":
      "w-variant-b3da03ef-e033-3453-3456-1cb102cc9fde",
    "golos/700/20/28/white": "w-variant-e75d5849-2b5d-657d-600c-68d32dc52ba6",
    "golos/700/18/28/white": "w-variant-38834777-d479-e5df-0c53-3eb8091d478d",
    "Inter/700/24/36/white": "w-variant-abdb4323-063c-d45f-95f7-156f9d3890ae",
    "Inter/700/24/36/black": "w-variant-3d1576e5-1eab-b237-cf49-d11729756ad9",
    "Inter/700/24:16/36:28/white":
      "w-variant-6493ea4a-33d5-7cce-2a48-4ffaae6ef53e",
    "Inter/700/16/28/white": "w-variant-2a232cf9-500c-efec-09ee-6df9dda6afeb",
    "Inter/700/16/28/blue": "w-variant-5e66309f-3156-dfd6-4ece-c64c03e1a198",
    "Inter/700/16/28/black": "w-variant-6611faa9-edb9-a33d-d47b-bb83430c9282",
    "Inter/700/14/20/blue": "w-variant-31b20c36-dbbe-13ca-cb3c-ce2ded5e0c3d",
    "Inter/700/14/20/black": "w-variant-2a3530db-349b-3f24-f020-2de56470df4e",
    "Inter/700/9/9/black": "w-variant-e783024a-a63a-48ff-69d6-cd33e4cc9eb5",
    "Inter/400/24/36/white": "w-variant-c2294178-8f56-9ee8-02d9-1d9caebc6bea",
    "Inter/400/16/28/white": "w-variant-43c2ced2-b4d3-3e65-38eb-e3095ed0533f",
    "Inter/400/16/28/grey": "w-variant-24deb08e-8aa1-1295-570c-c80dfeaef214",
    "Inter/400/16/28/black": "w-variant-ad058760-1da2-c65f-6247-6f3285c27ddc",
    "Inter/400/14/20/white": "w-variant-6af0e226-c43f-db39-948d-a5414080ce88",
    "Inter/400/14/20/light-grey":
      "w-variant-342d71c4-96ae-fd93-4186-5dfa0051234a",
    "Inter/400/14/20/dark-grey":
      "w-variant-86a7b1bc-5fea-2fbe-29f7-92ebad2c1a1f",
    "Inter/400/14:16/20:28/black":
      "w-variant-ea28ce7c-3d1e-6916-e2ad-26dd3a2c26dd",
    "Inter/400/12/16/dark-grey":
      "w-variant-c85e14a7-464c-d485-3ffe-c1b6f22cdb8a",
    "Roboto/700/16/24/green": "w-variant-82571113-6f5a-f1ea-01e5-762f4fac59ba",
    "Roboto/700/20/28/white": "w-variant-6fc64932-4eeb-1225-0122-efb8f381afb4",
    "Base (DONOT RESTYLE THIS ONE)": "",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Paragraph className={`copy-component-v7 ${_activeStyleVariant}`}>
        {text}
      </Paragraph>
    </div>
  );
}
