/**
 * @generated
 * @file Heading (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Heading2 from "../webflow_modules/Basic/components/Heading";

/**
 * Props for {@link Heading}
 */
export type HeadingProps = {
  title?: React.ReactNode;
  titleTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  variant?:
    | "h1 (84:43/92:51)"
    | "h1 (84:40/92:48)"
    | "h2"
    | "Base (DONOT RESTYLE)";
};

/**
 * Heading
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function Heading({
  title = <> </>,
  titleTag = "h1",
  variant = "Base (DONOT RESTYLE)",
}: HeadingProps) {
  const _styleVariantMap = {
    "h1 (84:43/92:51)": "w-variant-04aaba2a-32ce-0db9-c971-49bb32fc1f7e",
    "h1 (84:40/92:48)": "w-variant-f17f79e7-efda-141a-20b7-1d3d62051562",
    h2: "w-variant-8a1a65a6-649c-b7a5-4331-01548e4a3c5b",
    "Base (DONOT RESTYLE)": "",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Heading2 className={`c-heading ${_activeStyleVariant}`} tag={titleTag}>
        {title}
      </Heading2>
    </div>
  );
}
