/**
 * @generated
 * @file Article (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link Article}
 */
export type ArticleProps = {};

/**
 * Article
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function Article({}: ArticleProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"contribution-card"}
        id={"w-node-dbd104a2-abc8-4e71-8163-81c1d7bc6d6a-d7bc6d6a"}
        options={{
          href: "https://scandiweb.com/blog/",
        }}
      >
        <Image
          alt={""}
          className={"know-us-image"}
          height={"auto"}
          loading={"lazy"}
          src={
            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6231fcf731bfcc3825ea1a56_Data-informed%20eCommerce%20redesign%20(1)%20(1).avif"
          }
          width={"auto"}
        />
        <Heading className={"h3"} tag={"h3"}>
          {"Webinars, eBooks, and blog"}
        </Heading>
      </Link>
    </div>
  );
}
