/**
 * @generated
 * @file ButtonFullV7 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link ButtonFullV7}
 */
export type ButtonFullV7Props = {
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
  variant?:
    | "Base"
    | "orange-bg/white-text"
    | "blue-border/blue-text/max:full-width"
    | "white-border/white-text/max:full-width";
};

/**
 * ButtonFullV7
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ButtonFullV7({
  link = {
    href: "#",
  },

  text = "Get in touch",
  variant = "Base",
}: ButtonFullV7Props) {
  const _styleVariantMap = {
    Base: "",
    "orange-bg/white-text": "w-variant-ae970d71-522d-57cf-22cc-1d79f7d663eb",
    "blue-border/blue-text/max:full-width":
      "w-variant-f5207847-7cc3-e296-ac75-299d455be406",
    "white-border/white-text/max:full-width":
      "w-variant-a78b7432-c3a2-be4d-b3c2-25a0c4b3e611",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={""}
        button={true}
        className={`button-full-v7 ${_activeStyleVariant}`}
        options={link}
      >
        {text}
      </Link>
    </div>
  );
}
