// @ts-nocheck — DevLink-generated, see CLAUDE.md context/40-rules.md
/**
 * @generated
 * @file ClientLogos (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Grid from "./webflow_modules/Layout/components/Grid";
import Icon from "./webflow_modules/Icon/components/Icon";
import Image from "./webflow_modules/Basic/components/Image";
import SliderArrow from "./webflow_modules/Slider/components/SliderArrow";
import SliderMask from "./webflow_modules/Slider/components/SliderMask";
import SliderNav from "./webflow_modules/Slider/components/SliderNav";
import SliderSlide from "./webflow_modules/Slider/components/SliderSlide";
import SliderWrapper from "./webflow_modules/Slider/components/SliderWrapper";

/**
 * Props for {@link ClientLogos}
 */
export type ClientLogosProps = {};

/**
 * ClientLogos
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ClientLogos({}: ClientLogosProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Grid className={"gp-grid-94"} tag={"div"}>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={true}
          className={"logos-slider"}
          delay={3500}
          disableSwipe={true}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"w-node-_56c62aee-3033-dbf2-b46f-4c6cba1ac308-ba1ac307"}
          infinite={true}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"mask-4"}>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-723"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61c092be3e6c0d4423ecfab2_themetlogo2%201.avif"
                  }
                  width={"auto"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cc3ac2335b215d151d4085_puma.svg"
                  }
                  width={"669.5"}
                />
              </Block>
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"left-arrow-5"} dir={"left"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-left",
              }}
            />
          </SliderArrow>
          <SliderArrow className={"right-arrow-5"} dir={"right"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-right",
              }}
            />
          </SliderArrow>
          <SliderNav className={"slide-nav-3"} />
        </SliderWrapper>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={true}
          className={"logos-slider"}
          delay={5300}
          disableSwipe={true}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"w-node-_56c62aee-3033-dbf2-b46f-4c6cba1ac315-ba1ac307"}
          infinite={true}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"mask-4"}>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725 max-70"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61c092ed01ea017e784821a9_surface512832.avif"
                  }
                  width={"56.5"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cc1572446fd6ef34d680b8_lafayette-148.svg"
                  }
                  width={"297"}
                />
              </Block>
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"left-arrow-5"} dir={"left"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-left",
              }}
            />
          </SliderArrow>
          <SliderArrow className={"right-arrow-5"} dir={"right"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-right",
              }}
            />
          </SliderArrow>
          <SliderNav className={"slide-nav-3"} />
        </SliderWrapper>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={true}
          className={"logos-slider wider"}
          delay={4140}
          disableSwipe={true}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"w-node-_56c62aee-3033-dbf2-b46f-4c6cba1ac322-ba1ac307"}
          infinite={true}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"mask-4"}>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725 wider"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cc461650b8fe8cd0c02076_new-york-times.svg"
                  }
                  width={"176"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-724 max-60"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61efcad82a3e14eda7b56361_buff_rotated%20(1).svg"
                  }
                  width={"auto"}
                />
              </Block>
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"left-arrow-5"} dir={"left"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-left",
              }}
            />
          </SliderArrow>
          <SliderArrow className={"right-arrow-5"} dir={"right"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-right",
              }}
            />
          </SliderArrow>
          <SliderNav className={"slide-nav-3"} />
        </SliderWrapper>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={true}
          className={"logos-slider bp-427-hidden"}
          delay={5720}
          disableSwipe={true}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"w-node-_56c62aee-3033-dbf2-b46f-4c6cba1ac32f-ba1ac307"}
          infinite={true}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"mask-4"}>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725 wider"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cb350dcd0e3cd435f05b68_thomson-reuters.svg"
                  }
                  width={"auto"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cb3406b3273f7c7ba13b45_happy%20socks.svg"
                  }
                  width={"200"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725 wider"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cc3a301338a6fe9452608b_country%20casual%20teak.svg"
                  }
                  width={"200"}
                />
              </Block>
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"left-arrow-5"} dir={"left"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-left",
              }}
            />
          </SliderArrow>
          <SliderArrow className={"right-arrow-5"} dir={"right"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-right",
              }}
            />
          </SliderArrow>
          <SliderNav className={"slide-nav-3"} />
        </SliderWrapper>
        <SliderWrapper
          animation={"slide"}
          autoMax={0}
          autoplay={true}
          className={"logos-slider bp-374-hidden"}
          delay={4600}
          disableSwipe={true}
          duration={500}
          easing={"ease"}
          hideArrows={false}
          iconArrows={true}
          id={"w-node-_56c62aee-3033-dbf2-b46f-4c6cba1ac33f-ba1ac307"}
          infinite={true}
          navInvert={false}
          navNumbers={false}
          navRound={true}
          navShadow={false}
          navSpacing={3}
        >
          <SliderMask className={"mask-4"}>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cb353589882435abc99c7d_stefanel.svg"
                  }
                  width={"140"}
                />
              </Block>
            </SliderSlide>
            <SliderSlide tag={"div"}>
              <Block className={"div-block-211"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-725"}
                  height={"auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/61cb3365f08b9f4ac2102c5a_bonnier.svg"
                  }
                  width={"326"}
                />
              </Block>
            </SliderSlide>
          </SliderMask>
          <SliderArrow className={"left-arrow-5"} dir={"left"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-left",
              }}
            />
          </SliderArrow>
          <SliderArrow className={"right-arrow-5"} dir={"right"}>
            <Icon
              widget={{
                type: "icon",
                icon: "slider-right",
              }}
            />
          </SliderArrow>
          <SliderNav className={"slide-nav-3"} />
        </SliderWrapper>
      </Grid>
    </div>
  );
}
