/**
 * @generated
 * @file CtaBanner (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Span from "./webflow_modules/Basic/components/Span";

/**
 * Props for {@link CtaBanner}
 */
export type CtaBannerProps = {
  heroText?: React.ReactNode;
};

/**
 * CtaBanner
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function CtaBanner({ heroText = "Let's build" }: CtaBannerProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"banner_section banner_one"} tag={"div"}>
        <Block className={"div-block-1406 cenetred no"} tag={"div"}>
          <Heading
            className={"heading-294 centered black _20px h2_bold"}
            tag={"h2"}
          >
            {"Let's build"}
            <Span className={"text-span-203 white"}>
              {" something great together"}
            </Span>
          </Heading>
          <Block className={"text-block-303"} tag={"div"}>
            {
              "Planning a new store, expanding to global markets, or looking to adopt latest technology? Reach out to us, and let's make it happen."
            }
          </Block>
          <Block className={"div-block-1515"} tag={"div"}>
            <Link
              block={"inline"}
              button={false}
              className={"link-block-34"}
              options={{
                href: "/contact",
              }}
            >
              <Image
                alt={""}
                className={"hide-on-mobile persons"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6835cf6db25494bcc425bb4c_image%20432.png"
                }
                width={"auto"}
              />
              <Block className={"text-block-304"} tag={"div"}>
                {"Book a consultation"}
              </Block>
            </Link>
            <Link
              block={""}
              button={true}
              className={"cta_white stroke"}
              options={{
                href: "https://scandiweb.com/services",
                target: "_blank",
              }}
            >
              {"All services"}
            </Link>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
