/**
 * @generated
 * @file DropdownBlock (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import BackgroundVideoWrapper from "./webflow_modules/BackgroundVideo/components/BackgroundVideoWrapper";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link DropdownBlock}
 */
export type DropdownBlockProps = {
  image1?: string;
  image2?: string;
  link1?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  link2?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  link3?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  link4?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  title?: React.ReactNode;
};

/**
 * DropdownBlock
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function DropdownBlock({
  image1 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addabe66d1ca9a3433c140_Alfreds-Genkins.avif",
  image2 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addabef1952d14d8384e94_Kaspars-Kalkis.avif",

  link1 = {
    href: "/contact",
  },

  link2 = {
    href: "https://scandiweb.com/services",
    target: "_blank",
  },

  link3 = {
    href: "/contact",
  },

  link4 = {
    href: "https://scandiweb.com/services",
    target: "_blank",
  },

  title = "Tech & development",
}: DropdownBlockProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"dropdown_block"} tag={"div"}>
        <Block className={"dropdown_content "} tag={"div"}>
          <BackgroundVideoWrapper
            autoPlay={true}
            className={"accordeon-background-video"}
            loop={true}
            posterImage={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-poster-00001.jpg"
            }
            sources={[
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.webm",
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.mp4",
            ]}
            tag={"div"}
          />
          <Block className={"div-block-1371"} tag={"div"}>
            <Heading className={"h3_text"} tag={"h3"}>
              {title}
            </Heading>
            <Block className={"link_texts"} tag={"div"}>
              <Block className={"text-block-257"} tag={"div"}>
                {"eCommerce development"}
              </Block>
              <Block className={"text-block-257"} tag={"div"}>
                {"App development"}
              </Block>
              <Block className={"text-block-257"} tag={"div"}>
                {"Custom development"}
              </Block>
              <Block className={"text-block-257  no-stroke"} tag={"div"}>
                {"Modernization"}
              </Block>
            </Block>
            <Block className={"cta-buttons hide-on-mobile"} tag={"div"}>
              <Link
                block={""}
                button={true}
                className={"cta_white"}
                options={link1}
              >
                {"Book a consultation"}
              </Link>
              <Link
                block={""}
                button={true}
                className={"cta_transparent"}
                options={link2}
              >
                {"All services"}
              </Link>
            </Block>
          </Block>
          <Block className={"text_persons"} tag={"div"}>
            <Block className={"dropdown-text-block"} tag={"div"}>
              {
                "Platform migrations, custom development, ERP, PIM, OMS, and CDP integrations. Our solutions offer flexibility, performance, and ongoing technical improvements for speed and security."
              }
            </Block>
            <Block className={"person_block"} tag={"div"}>
              <Block className={"dropdown-person-item"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-4286"}
                  height={"auto"}
                  loading={"eager"}
                  src={image1}
                  width={"56"}
                />
                <Block className={"div-block-1373"} tag={"div"}>
                  <Block className={"text-block-259"} tag={"div"}>
                    {"Alfreds Genkins"}
                  </Block>
                  <Block className={"caption_text"} tag={"div"}>
                    {"CTO"}
                  </Block>
                </Block>
              </Block>
              <Block className={"dropdown-person-item"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-4286"}
                  height={"auto"}
                  loading={"eager"}
                  src={image2}
                  width={"56"}
                />
                <Block className={"div-block-1373"} tag={"div"}>
                  <Block className={"text-block-259"} tag={"div"}>
                    {"Kaspars Kalkis"}
                  </Block>
                  <Block className={"caption_text"} tag={"div"}>
                    {"Tech Strategy Lead"}
                  </Block>
                </Block>
              </Block>
            </Block>
          </Block>
          <Block className={"cta-buttons hide-on-desktop"} tag={"div"}>
            <Link
              block={""}
              button={true}
              className={"cta_white"}
              options={link3}
            >
              {"Book a consultation"}
            </Link>
            <Link
              block={""}
              button={true}
              className={"cta_transparent"}
              options={link4}
            >
              {"All services"}
            </Link>
          </Block>
          <HtmlEmbed
            className={"drop-open"}
            content={""}
            id={"drop-open"}
            value={
              "%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2020%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M7.38818%2019H12.6117V12.6118H19V7.38831H12.6117V1H7.38818L7.38818%207.38831H1V12.6118H7.38818L7.38818%2019Z%22%20fill%3D%22%23F8F4EF%22%2F%3E%0A%3C%2Fsvg%3E"
            }
          />
        </Block>
      </Block>
    </div>
  );
}
