/**
 * @generated
 * @file Experts (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link Experts}
 */
export type ExpertsProps = {
  caption2Text?: React.ReactNode;
};

/**
 * Experts
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function Experts({
  caption2Text = "London, United Kingdom",
}: ExpertsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"div-flex experts"} tag={"div"}>
        <Block className={"div-flex inner"} tag={"div"}>
          <Image
            alt={""}
            className={" image-33"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6183cce6252e4d7308bc415b_Group%201152%20(5).avif"
            }
            width={"104"}
          />
          <Block className={"expert"} tag={"div"}>
            <Block className={"text-block-grey-2 mb-8"} tag={"div"}>
              {"Aigars Pavlovics"}
            </Block>
            <Block className={"text-block-10 small experts bold"} tag={"div"}>
              {"+371 28 346 764"}
            </Block>
            <Block className={"text-block-10 small experts"} tag={"div"}>
              {"lv@scandiweb.com"}
            </Block>
            <Block className={"caption-2"} tag={"div"}>
              <Link
                block={""}
                button={false}
                options={{
                  href: "#",
                }}
              >
                {"Riga"}
              </Link>
              {", Latvia"}
            </Block>
          </Block>
        </Block>
        <Block className={"div-flex inner"} tag={"div"}>
          <Image
            alt={""}
            className={" image-33"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6194df129c1d0480dceca389_Group%201153%20(10).avif"
            }
            width={"104"}
          />
          <Block className={"expert"} tag={"div"}>
            <Block className={"text-block-grey-2 mb-8"} tag={"div"}>
              {"Alex Tse"}
            </Block>
            <Block className={"text-block-10 small experts bold"} tag={"div"}>
              {"+44 7737 259337"}
            </Block>
            <Block className={"text-block-10 small experts"} tag={"div"}>
              {"alex@scandiweb.uk"}
            </Block>
            <Block className={"caption-2"} tag={"div"}>
              <Link
                block={""}
                button={false}
                options={{
                  href: "#",
                }}
              >
                {"London"}
              </Link>
              {", United Kingdom"}
            </Block>
          </Block>
        </Block>
        <Block className={"div-flex inner"} tag={"div"}>
          <Image
            alt={""}
            className={"image-40"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6183cd24cebb895c944bc583_Group%201153%20(5).avif"
            }
            width={"104"}
          />
          <Block className={"expert"} tag={"div"}>
            <Block className={"text-block-grey-2 mb-8"} tag={"div"}>
              {"Glebs Vrevskis"}
            </Block>
            <Block className={"text-block-10 small experts bold"} tag={"div"}>
              {"+1 985 720 0253"}
            </Block>
            <Block className={"text-block-10 small experts"} tag={"div"}>
              {"info@scandiweb.com"}
            </Block>
            <Block className={"caption-2"} tag={"div"}>
              <Link
                block={""}
                button={false}
                options={{
                  href: "#",
                }}
              >
                {"New York"}
              </Link>
              {", USA"}
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
