/**
 * @generated
 * @file HeaderScandilytics (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Icon from "./webflow_modules/Icon/components/Icon";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import NavbarBrand from "./webflow_modules/Navbar/components/NavbarBrand";
import NavbarButton from "./webflow_modules/Navbar/components/NavbarButton";
import NavbarContainer from "./webflow_modules/Navbar/components/NavbarContainer";
import NavbarLink from "./webflow_modules/Navbar/components/NavbarLink";
import NavbarMenu from "./webflow_modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";

/**
 * Props for {@link HeaderScandilytics}
 */
export type HeaderScandilyticsProps = {};

/**
 * HeaderScandilytics
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function HeaderScandilytics({}: HeaderScandilyticsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <NavbarWrapper
        className={"scandlilytics-hader px-16"}
        config={{
          animation: "default",
          collapse: "medium",
          docHeight: false,
          duration: 400,
          easing: "ease",
          easing2: "ease",
          noScroll: false,
        }}
        tag={"div"}
      >
        <NavbarContainer className={"nav-container"} tag={"div"}>
          <Block className={"scandilytics-navbar"} tag={"div"}>
            <NavbarBrand
              options={{
                href: "/scandilytics",
              }}
            >
              <Image
                alt={""}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/63fefebd5ce6533ab6e01b64_scandi.svg"
                }
                width={"auto"}
              />
            </NavbarBrand>
            <Block className={"navigation-menu"} tag={"div"}>
              <NavbarMenu
                className={"nav-menu-5 centered"}
                role={"navigation"}
                tag={"nav"}
              >
                <Block className={"link-badge"} tag={"div"}>
                  <Block className={"badge-new"} tag={"div"}>
                    <Block className={"text-block-164"} tag={"div"}>
                      {"new"}
                    </Block>
                  </Block>
                  <NavbarLink
                    className={"nav-link-menu"}
                    options={{
                      href: "https://www.scandilytics.ai/",
                      target: "_blank",
                    }}
                  >
                    {"AnalyticsAI"}
                  </NavbarLink>
                </Block>
                <NavbarLink
                  className={"nav-link-menu"}
                  options={{
                    href: "/scandilytics-2/problems-we-solve",
                  }}
                >
                  {"Problems we solve"}
                </NavbarLink>
                <NavbarLink
                  className={"nav-link-menu"}
                  options={{
                    href: "https://scandiweb.com/scandilytics#Service-we-offer",
                  }}
                >
                  {"Services"}
                </NavbarLink>
                <Link
                  block={""}
                  button={true}
                  className={"cta"}
                  options={{
                    href: "/contact",
                  }}
                >
                  {"Contact us"}
                </Link>
              </NavbarMenu>
            </Block>
            <NavbarButton className={" menu-button-5"} tag={"div"}>
              <Icon
                className={"icon-3"}
                widget={{
                  type: "icon",
                  icon: "nav-menu",
                }}
              />
            </NavbarButton>
          </Block>
        </NavbarContainer>
      </NavbarWrapper>
    </div>
  );
}
