/**
 * @generated
 * @file KnowlageBlok (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Grid from "./webflow_modules/Layout/components/Grid";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";

/**
 * Props for {@link KnowlageBlok}
 */
export type KnowlageBlokProps = {};

/**
 * KnowlageBlok
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function KnowlageBlok({}: KnowlageBlokProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Grid className={"blog-grid"} tag={"div"}>
        <Block className={"contribution-card-2"} tag={"div"}>
          <Image
            alt={""}
            className={"blog-grid-image"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/625ea88038b4ef8947945889_6tips.avif"
            }
            width={"auto"}
          />
          <List className={"list-4"} tag={"ul"} unstyled={false}>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/301-redirect-mapping-guide-for-magento-2/",
                }}
              >
                {"Magento 301 Redirect Mapping: Ultimate Guide"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={"badge-2 communiti-grid-badge primary-green"}
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"SEO"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/ecommerce-personalization-tools-that-drive-sales/",
                }}
              >
                {
                  "AI-Powered Personalization for Search, Product Upsell, and Merchandising"
                }
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={"badge-2 communiti-grid-badge primary-orange"}
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"TECHNOLOGY"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/ga4-vs-universal-analytics/",
                }}
              >
                {
                  "What Does Google Analytics 4 Do Better than Universal Analytics?"
                }
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={"badge-2 communiti-grid-badge blue"}
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"ANALYTICS"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
          </List>
          <Link
            block={""}
            button={true}
            className={"cta-black tp-40"}
            options={{
              href: "https://scandiweb.com/blog/",
              target: "_blank",
            }}
          >
            {"Go to Blog"}
          </Link>
        </Block>
        <Block className={"contribution-card-2"} tag={"div"}>
          <Image
            alt={""}
            className={"blog-grid-image"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/625ea88c03bfba869f1b110d_seo.avif"
            }
            width={"454.5"}
          />
          <List className={"list-4"} tag={"ul"} unstyled={false}>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-usability-testing/",
                }}
              >
                {"6 Usability Tests to Increase Mobile Conversions"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={"badge-2 communiti-grid-badge primary-yellow"}
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"CX"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-16lp"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-effective-seo-strategies-roundtable/",
                }}
              >
                {"Effective SEO Strategies in 2021"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={
                    "badge-2 communiti-grid-badge primary-green strategic"
                  }
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"SEO"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-16lp"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-marello-and-magento/",
                }}
              >
                {"Marello + Magento: Unified eCommerce "}
                <br />
                {"backend automation"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={
                    "badge-2 communiti-grid-badge primary-green uniecomerce"
                  }
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"PLATFORMS"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
          </List>
          <Link
            block={""}
            button={true}
            className={"cta-black tp-40"}
            options={{
              href: "https://scandiweb.com/blog/knowledge-webinars/",
              target: "_blank",
            }}
          >
            {"Participate in Webinars"}
          </Link>
        </Block>
        <Block className={"contribution-card-2"} tag={"div"}>
          <Image
            alt={""}
            className={"blog-grid-image ebook"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/625ea9457ed0c90ca6f8941b_webinar.avif"
            }
            width={"291"}
          />
          <List className={"list-4"} tag={"ul"} unstyled={false}>
            <ListItem className={"community-grid-list-item mt-16lp"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-marello-and-magento/",
                }}
              >
                {"PWA-Specific Magento & React Methodology"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={
                    "badge-2 communiti-grid-badge primary-green uniecomerce"
                  }
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"TECHNOLOGY"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-16lp"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-data-tracking-for-pwa/",
                }}
              >
                {"Transitioning to GA4:The Future of Analytics"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={"badge-2 communiti-grid-badge blue"}
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"ANALYTICS"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-16lp"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://scandiweb.com/blog/webinar-effective-seo-strategies-roundtable/",
                }}
              >
                {"Best SEOPractices in eCommerce"}
              </Link>
              <Block className={"grid-badge-wrapper"} tag={"div"}>
                <Block
                  className={
                    "badge-2 communiti-grid-badge primary-green strategic"
                  }
                  tag={"div"}
                >
                  <Block className={"form-block-badge-text-2"} tag={"div"}>
                    {"SEO"}
                  </Block>
                </Block>
              </Block>
            </ListItem>
          </List>
          <Link
            block={""}
            button={true}
            className={"cta-black tp-40"}
            options={{
              href: "https://scandiweb.com/blog/knowledge/",
              target: "_blank",
            }}
          >
            {"Ebooks & Checklists"}
          </Link>
        </Block>
        <Block
          className={"contribution-card-2"}
          id={"w-node-_0d4c225e-d0b3-3690-df06-df86878f8e7a-878f8e28"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"blog-grid-image big shift-left mb-0"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/624af5ea773b0d47713914f7_Group%202933.avif"
            }
            width={"414.5"}
          />
          <List className={"list-4"} tag={"ul"} unstyled={false}>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://www.youtube.com/watch?v=aM9Cm5Rda2w&list=PLdJMTS5lg1De6FaHk27bwFGvaMOC6sYwd",
                  target: "_blank",
                }}
              >
                {"eCom360: Adapt or Lose 2021"}
                <br />
              </Link>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://ecom360.io/worldwide-events",
                  target: "_blank",
                }}
              >
                {"eCom360: Only-online warm up 2020"}
              </Link>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://www.youtube.com/watch?v=_OVWW6X7uzI&t=5s",
                  target: "_blank",
                }}
              >
                {"eCom360: East meet West 2019"}
              </Link>
            </ListItem>
            <ListItem className={"community-grid-list-item mt-40"}>
              <Link
                block={""}
                button={false}
                className={"contribution-link-2"}
                options={{
                  href: "https://meetmagentobaltics.com/",
                  target: "_blank",
                }}
              >
                {"Meet Magento Baltics"}
              </Link>
            </ListItem>
          </List>
          <Link
            block={""}
            button={true}
            className={"cta-black tp-40"}
            options={{
              href: "https://www.youtube.com/c/Scandiwebcom/playlists?view=50&sort=dd&shelf_id=2",
              target: "_blank",
            }}
          >
            {"Visit Events"}
          </Link>
        </Block>
      </Grid>
    </div>
  );
}
