/**
 * @generated
 * @file MainContactForm (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import FormBlockLabel from "./webflow_modules/Form/components/FormBlockLabel";
import FormButton from "./webflow_modules/Form/components/FormButton";
import FormErrorMessage from "./webflow_modules/Form/components/FormErrorMessage";
import FormForm from "./webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "./webflow_modules/Form/components/FormSuccessMessage";
import FormTextarea from "./webflow_modules/Form/components/FormTextarea";
import FormTextInput from "./webflow_modules/Form/components/FormTextInput";
import FormWrapper from "./webflow_modules/Form/components/FormWrapper";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link MainContactForm}
 */
export type MainContactFormProps = {};

/**
 * MainContactForm
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function MainContactForm({}: MainContactFormProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <FormWrapper className={"form-block-2"}>
        <FormForm
          data-name={"Email Form"}
          id={"wf-form-Email-Form"}
          method={"get"}
          name={"wf-form-Email-Form"}
        >
          <Block className={"form-field"} tag={"div"}>
            <FormBlockLabel
              className={"input-label text-block"}
              htmlFor={"name-2"}
            >
              {"Hey, my name is"}
            </FormBlockLabel>
            <FormTextInput
              autoFocus={false}
              className={"input-2 name-input"}
              data-name={"Name 2"}
              disabled={false}
              id={"name-2"}
              maxLength={256}
              name={"name-2"}
              placeholder={"Type here"}
              required={false}
              type={"text"}
            />
          </Block>
          <Block className={"form-field"} tag={"div"}>
            <FormBlockLabel
              className={"input-label text-block"}
              htmlFor={"Contacts-3"}
            >
              {"Get in touch with me at"}
            </FormBlockLabel>
            <FormTextInput
              autoFocus={false}
              className={"input-2 contacts-input"}
              data-name={"Contacts 2"}
              disabled={false}
              id={"Contacts-2"}
              maxLength={256}
              name={"Contacts-2"}
              placeholder={"Your email or phone"}
              required={false}
              type={"text"}
            />
          </Block>
          <Block className={"form-field"} tag={"div"}>
            <FormBlockLabel
              className={"input-label text-block"}
              htmlFor={"Website-3"}
            >
              {"Here is my website"}
            </FormBlockLabel>
            <FormTextInput
              autoFocus={false}
              className={"input-2 website-input"}
              data-name={"Website 2"}
              disabled={false}
              id={"Website-2"}
              maxLength={256}
              name={"Website-2"}
              placeholder={"Your website link"}
              required={false}
              type={"text"}
            />
          </Block>
          <FormBlockLabel
            className={"input-label text-block last"}
            htmlFor={"Info-2"}
          >
            {"Can you help me with...?"}
          </FormBlockLabel>
          <FormTextarea
            autoFocus={false}
            className={"input-2 info-iinput"}
            data-name={"Info 2"}
            id={"Info-2"}
            maxLength={5000}
            name={"Info-2"}
            placeholder={"Your text"}
            required={false}
          />
          <Block className={"submit-block"} tag={"div"}>
            <FormButton
              className={"cta mobile-full-w"}
              data-wait={"Please wait..."}
              type={"submit"}
              value={"Get In Touch Now!"}
            />
            <Image
              alt={""}
              className={"image-216"}
              height={"auto"}
              loading={"lazy"}
              src={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/618e4402f8ffcc68bea83b30_Waves%20(2).svg"
              }
              width={"auto"}
            />
          </Block>
        </FormForm>
        <FormSuccessMessage>
          <Block tag={"div"}>
            {"Thank you! Your submission has been received!"}
          </Block>
        </FormSuccessMessage>
        <FormErrorMessage>
          <Block tag={"div"}>
            {"Oops! Something went wrong while submitting the form."}
          </Block>
        </FormErrorMessage>
      </FormWrapper>
    </div>
  );
}
