/**
 * @generated
 * @file SectionCaseStudies (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Span from "./webflow_modules/Basic/components/Span";
import Strong from "./webflow_modules/Basic/components/Strong";
import TabsContent from "./webflow_modules/Tabs/components/TabsContent";
import TabsLink from "./webflow_modules/Tabs/components/TabsLink";
import TabsMenu from "./webflow_modules/Tabs/components/TabsMenu";
import TabsPane from "./webflow_modules/Tabs/components/TabsPane";
import TabsWrapper from "./webflow_modules/Tabs/components/TabsWrapper";

/**
 * Props for {@link SectionCaseStudies}
 */
export type SectionCaseStudiesProps = {};

/**
 * SectionCaseStudies
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function SectionCaseStudies({}: SectionCaseStudiesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"tabs_sections"} tag={"div"}>
        <Block className={" div-block-1508"} tag={"div"}>
          <Block className={"div-block-1505 top"} tag={"div"}>
            <Heading className={" heading-293 no_pad large"} tag={"h2"}>
              <Span className={" text-span-194"}>{"Discover "}</Span>
              {"case studies worth reading"}
            </Heading>
            <Link
              block={""}
              button={true}
              className={"cta_blue"}
              options={{
                href: "https://scandiweb.com/knowledge",
                target: "_blank",
              }}
            >
              {"Explore more"}
            </Link>
          </Block>
          <Block className={"tab-block"} tag={"div"}>
            <TabsWrapper
              className={"tabs-6"}
              current={"Tab 1"}
              easing={"ease"}
              fadeIn={300}
              fadeOut={100}
            >
              <TabsMenu className={" tabs-menu-8"} tag={"div"}>
                <TabsLink
                  block={"inline"}
                  className={"tab-link-tab-1-4"}
                  data-w-tab={"Tab 1"}
                >
                  <Block className={"text-block-299"} tag={"div"}>
                    {"Blog"}
                  </Block>
                </TabsLink>
                <TabsLink
                  block={"inline"}
                  className={"tab-link-tab-1-4"}
                  data-w-tab={"Tab 2"}
                >
                  <Block tag={"div"}>{"Webinar"}</Block>
                </TabsLink>
                <TabsLink
                  block={"inline"}
                  className={"tab-link-tab-1-4"}
                  data-w-tab={"Tab 3"}
                >
                  <Block tag={"div"}>{"eBooks"}</Block>
                </TabsLink>
              </TabsMenu>
              <TabsContent className={" tabs-content-4"} tag={"div"}>
                <TabsPane
                  className={"tab-pane-tab-1-2"}
                  data-w-tab={"Tab 1"}
                  tag={"div"}
                >
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first"}
                    options={{
                      href: "https://scandiweb.com/blog/how-retailers-are-building-software-10x-faster/",
                      target: "_blank",
                    }}
                  >
                    <Heading className={" heading-300"} tag={"h3"}>
                      <Strong className={"bold-text-70"}>
                        {
                          "How Retailers Are Building Software 10x Faster, 90% Cheaper"
                        }
                      </Strong>
                    </Heading>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "From €4M to €0.25M and 1.5 years to 14 weeks – see how retailers are rebuilding systems faster and at a fraction of the cost."
                      }
                    </Block>
                    <Block className={" div-block-1509"} tag={"div"}>
                      <Image
                        alt={""}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69d5e613291ba5a24f7e3010_Aigars%20Pavlovics.png"
                        }
                        width={"36"}
                      />
                      <Block className={"text-block-259 black"} tag={"div"}>
                        <Strong>{"Aigars Pavlovics"}</Strong>
                      </Block>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"Apr 02, 2026"}
                      </Block>
                    </Block>
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first last"}
                    options={{
                      href: "https://scandiweb.com/blog/chat-to-buy/",
                      target: "_blank",
                    }}
                  >
                    <Heading className={" heading-300"} tag={"h3"}>
                      <Strong>
                        {
                          "Chat to Buy: The Future of eCommerce Is Conversational"
                        }
                      </Strong>
                    </Heading>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "Introducing the conversational commerce solution that makes chats into personalized shopping experiences your customers will love."
                      }
                    </Block>
                    <Block className={" div-block-1509"} tag={"div"}>
                      <Image
                        alt={""}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69d5e688a0a1b3e4919997ad_Glebs-Vrevskis.png"
                        }
                        width={"36"}
                      />
                      <Block className={"text-block-259 black"} tag={"div"}>
                        <Strong>{"Glebs Vrevsky"}</Strong>
                      </Block>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"Nov 04, 2025"}
                      </Block>
                    </Block>
                  </Link>
                </TabsPane>
                <TabsPane data-w-tab={"Tab 2"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first"}
                    options={{
                      href: "https://scandiweb.com/resources/ai-search-webinar",
                      target: "_blank",
                    }}
                  >
                    <Heading className={" heading-300"} tag={"h3"}>
                      {
                        "How to become the recommended B2C omnichannel retail brand in AI search"
                      }
                    </Heading>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "For €100M–€2B B2C omni-channel retail brands, growth is no longer only driven by traffic and campaigns - it’s driven by who gets recommended when shoppers research and compare options."
                      }
                    </Block>
                    <Block className={" div-block-1509"} tag={"div"}>
                      <Heading className={" heading-299"} tag={"h3"}>
                        <Strong className={"bold-text-68"}>
                          {"Free webinar"}
                        </Strong>
                      </Heading>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"January 29, 2026"}
                      </Block>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"3:00 p.m. (GMT)"}
                      </Block>
                    </Block>
                    <Block className={" div-block-1509 _20px"} tag={"div"}>
                      <Image
                        alt={""}
                        className={"image-4257 _42px"}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6965f64eef4239c96d1b8f25_SW%20Expert%20circle%20(2)%20(1).png"
                        }
                        width={"auto"}
                      />
                      <Block className={"div-block-1510"} tag={"div"}>
                        <Block className={"text-block-259 black"} tag={"div"}>
                          <Strong>{"Janis Sarmulis"}</Strong>
                        </Block>
                        <Block className={" text-block-300"} tag={"div"}>
                          {"AEO Strategist"}
                        </Block>
                      </Block>
                    </Block>
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first last"}
                    options={{
                      href: "https://scandiweb.com/resources/growing-online-sales-webinar",
                      target: "_blank",
                    }}
                  >
                    <Heading className={" heading-300"} tag={"h3"}>
                      <Strong>
                        {
                          "Growing online sales for brick-n-mortar retail in 2025"
                        }
                      </Strong>
                    </Heading>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "Learn how to tackle the key challenges retailers face, bridge the gap between physical and online stores, improve customer experiences, and stay ahead of the competition."
                      }
                    </Block>
                    <Block className={" div-block-1509"} tag={"div"}>
                      <Heading className={" heading-299"} tag={"h3"}>
                        <Strong className={"bold-text-69"}>
                          {"Free webinar"}
                        </Strong>
                      </Heading>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"March 5, 2025"}
                      </Block>
                      <Block className={" text-block-300"} tag={"div"}>
                        {"4:00 p.m. (GMT)"}
                      </Block>
                    </Block>
                    <Block className={" div-block-1509 _20px"} tag={"div"}>
                      <Block className={"div-block-1511"} tag={"div"}>
                        <Image
                          alt={""}
                          className={"image-4257 _42px"}
                          height={"auto"}
                          loading={"eager"}
                          src={
                            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/68359b81156b678a2912ed98_image%20(4).png"
                          }
                          width={"auto"}
                        />
                        <Block className={"div-block-1510"} tag={"div"}>
                          <Block className={"text-block-259 black"} tag={"div"}>
                            <Strong>{"Reinis Groskops"}</Strong>
                          </Block>
                          <Block className={" text-block-300"} tag={"div"}>
                            {"Head of Analytics"}
                          </Block>
                        </Block>
                      </Block>
                      <Block className={"div-block-1511"} tag={"div"}>
                        <Image
                          alt={""}
                          className={"image-4257 _42px"}
                          height={"auto"}
                          loading={"eager"}
                          src={
                            "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/68359c851902f87e123cc807_image%20(5).png"
                          }
                          width={"auto"}
                        />
                        <Block className={"div-block-1510"} tag={"div"}>
                          <Block className={"text-block-259 black"} tag={"div"}>
                            <Strong>{"Reinis Groskops"}</Strong>
                          </Block>
                          <Block className={" text-block-300"} tag={"div"}>
                            {"Lead CRO Strategist"}
                          </Block>
                        </Block>
                      </Block>
                    </Block>
                  </Link>
                </TabsPane>
                <TabsPane data-w-tab={"Tab 3"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first"}
                    options={{
                      href: "https://scandiweb.com/resources/enterprise-cms-platforms-for-ecommerce",
                      target: "_blank",
                    }}
                  >
                    <Block className={"book-header"} tag={"div"}>
                      <Image
                        alt={""}
                        className={"image-4258"}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/68359e8e4204cd0e3727a12e_image%20(7).png"
                        }
                        width={"auto"}
                      />
                      <Block className={"div-block-1513"} tag={"div"}>
                        <Heading className={" heading-300 no_pad"} tag={"h3"}>
                          <Strong>
                            {"Enterprise CMS platforms for eCommerce"}
                          </Strong>
                        </Heading>
                        <Heading className={" heading-299"} tag={"h3"}>
                          <Strong className={"bold-text-68"}>
                            {"Free webinar"}
                          </Strong>
                        </Heading>
                      </Block>
                    </Block>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "Customer data matters more than ever in 2025, but most eCommerce teams aren’t using it effectively."
                      }
                    </Block>
                    <Block className={" div-block-1509 _20px"} tag={"div"}>
                      <Image
                        alt={""}
                        className={"image-4257 _42px"}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6835a0f27460c0e285414d2c_Glebs-Vrevskis%20(2).png"
                        }
                        width={"auto"}
                      />
                      <Block className={"div-block-1510"} tag={"div"}>
                        <Block className={"text-block-259 black"} tag={"div"}>
                          <Strong>{"Alex Tse"}</Strong>
                        </Block>
                        <Block className={" text-block-300"} tag={"div"}>
                          {"CMS lead"}
                        </Block>
                      </Block>
                    </Block>
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"  blog_block first last"}
                    options={{
                      href: "https://scandiweb-resources.webflow.io/resources/pim-ecommerce-integration-research",
                      target: "_blank",
                    }}
                  >
                    <Block className={"book-header"} tag={"div"}>
                      <Image
                        alt={""}
                        className={"image-4258"}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6836fcd4f04e8193287ebad5_image%20(11).png"
                        }
                        width={"auto"}
                      />
                      <Block className={"div-block-1513"} tag={"div"}>
                        <Heading className={" heading-300 no_pad"} tag={"h3"}>
                          <Strong>
                            {
                              "PIM and eCommerce integration: What you need to know"
                            }
                          </Strong>
                        </Heading>
                        <Heading className={" heading-299"} tag={"h3"}>
                          <Strong className={"bold-text-68"}>
                            {"Free webinar"}
                          </Strong>
                        </Heading>
                      </Block>
                    </Block>
                    <Block className={" text-block-301"} tag={"div"}>
                      {
                        "Product Information Management (PIM) solution users can bring their products to market up to 60% faster. "
                      }
                    </Block>
                    <Block className={" div-block-1509 _20px"} tag={"div"}>
                      <Image
                        alt={""}
                        className={"image-4257 _42px"}
                        height={"auto"}
                        loading={"eager"}
                        src={
                          "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6835c8cfd646d4db9ff59d8e_Glebs-Vrevskis%20(3).png"
                        }
                        width={"auto"}
                      />
                      <Block className={"div-block-1510"} tag={"div"}>
                        <Block className={"text-block-259 black"} tag={"div"}>
                          <Strong>{"Ana Luisa Taylor"}</Strong>
                        </Block>
                        <Block className={" text-block-300"} tag={"div"}>
                          {"PIM lead"}
                        </Block>
                      </Block>
                    </Block>
                  </Link>
                </TabsPane>
              </TabsContent>
            </TabsWrapper>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
