/**
 * @generated
 * @file SeoServices (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Grid from "./webflow_modules/Layout/components/Grid";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";
import Strong from "./webflow_modules/Basic/components/Strong";

/**
 * Props for {@link SeoServices}
 */
export type SeoServicesProps = {};

/**
 * SeoServices
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function SeoServices({}: SeoServicesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"seo-services-section red purple"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"content-container"} tag={"div"}>
          <Block className={"div-block-17"} tag={"div"}>
            <Heading className={"magento-pages-heading"} tag={"h2"}>
              {"Other Magento & Adobe Commerce services"}
            </Heading>
            <Grid className={"grid magento-services"} tag={"div"}>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b089b-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-12"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/adobe-magento-2-migration",
                    target: "_blank",
                  }}
                >
                  {"Magento Migration"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b089f-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-12"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-support",
                    target: "_blank",
                  }}
                >
                  {"Magento Support"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08a3-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-14"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-upgrade-services",
                    target: "_blank",
                  }}
                >
                  {"Magento Upgrade"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08a7-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-15"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "#",
                    target: "_blank",
                  }}
                >
                  {"Magento Commerce Developers"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08ab-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-5"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-consulting",
                    target: "_blank",
                  }}
                >
                  {"Magento Consulting Services"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08af-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-5"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-website-development",
                    target: "_blank",
                  }}
                >
                  {"Magento Website Development"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08b3-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-5"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-integration-services",
                    target: "_blank",
                  }}
                >
                  {"Magento Integration"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08b7-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-7"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-design-service",
                    target: "_blank",
                  }}
                >
                  {"Magento Design"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08bb-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-8"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-performance-optimization",
                    target: "_blank",
                  }}
                >
                  {"Magento Optimization"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08bf-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-8"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-b2b",
                    target: "_blank",
                  }}
                >
                  {"Magento B2B"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08c3-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-8"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "https://scandiweb.com/services/magento-hosting",
                    target: "_blank",
                  }}
                >
                  {"Magento Hosting"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08c7-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-4"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%22auto%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-pwa",
                    target: "_blank",
                  }}
                >
                  {"Magento PWA"}
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08cb-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-9"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-react-development",
                    target: "_blank",
                  }}
                >
                  <Strong className={"bold-text-62"}>
                    {"Magento Front-end on React"}
                  </Strong>
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08d0-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-10"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-vue-js-development",
                    target: "_blank",
                  }}
                >
                  <Strong className={"bold-text-61"}>
                    {"Magento Front-end on Vue.js"}
                  </Strong>
                </Link>
              </Block>
              <Block
                className={"services-link-container new"}
                id={"w-node-_531a1aee-441b-816f-3ae7-6da6710b08d5-710b0895"}
                tag={"div"}
              >
                <HtmlEmbed
                  className={"code-embed-11"}
                  content={""}
                  value={
                    "%3Csvg%20width%3D%2220%22%20height%3D%2221%22%20viewBox%3D%220%200%2020%2021%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M10.0013%2018.5011C14.6037%2018.5011%2018.3346%2014.7702%2018.3346%2010.1678C18.3346%205.56543%2014.6037%201.83447%2010.0013%201.83447C5.39893%201.83447%201.66797%205.56543%201.66797%2010.1678C1.66797%2014.7702%205.39893%2018.5011%2010.0013%2018.5011Z%22%20fill%3D%22%2310132C%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%2F%3E%0A%3Cpath%20d%3D%22M8.75%206.83447C8.75%206.83447%2011.25%209.28947%2011.25%2010.1678C11.25%2011.0462%208.75%2013.5011%208.75%2013.5011%22%20stroke%3D%22%23C5CBFB%22%20stroke-width%3D%221.25%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3C%2Fsvg%3E"
                  }
                />
                <Link
                  block={""}
                  button={false}
                  className={"link-92"}
                  options={{
                    href: "/magento-services",
                    target: "_blank",
                  }}
                >
                  <Strong className={"bold-text-60"}>
                    {"Other Magento services"}
                  </Strong>
                </Link>
              </Block>
            </Grid>
          </Block>
        </Container>
        <HtmlEmbed
          className={"html-embed-14"}
          content={""}
          value={
            "%3Csvg%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%201440%2087%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M1316%2053.7649L1440%2086.4776L1440%200.000312813L1.51202e-05%20-2.28882e-05L1.76777e-05%2071.8864L40%2085.724L112%2071.8865L220.412%2085.724L319.264%2086.4776L419.916%2071.8864L524.2%2053.7648L618.144%2059.2754L718%2059.2754L821.066%2034.2971L919.357%2032.9726L1002%2059.2754L1114.3%2037.9243L1218%2037.9243L1316%2053.7649Z%22%20fill%3D%22%23EFF2F8%22%2F%3E%0A%3C%2Fsvg%3E"
          }
        />
      </Section>
    </div>
  );
}
