/**
 * @generated
 * @file ServicesWhite (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Grid from "./webflow_modules/Layout/components/Grid";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link ServicesWhite}
 */
export type ServicesWhiteProps = {};

/**
 * ServicesWhite
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ServicesWhite({}: ServicesWhiteProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"seo-services-section white"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"content-container"} tag={"div"}>
          <Block className={"div-block-17"} tag={"div"}>
            <Heading className={"magento-pages-heading"} tag={"h2"}>
              {"Our Magento services"}
            </Heading>
            <Grid className={"grid magento-services"} tag={"div"}>
              <Link
                block={"inline"}
                button={false}
                className={"default-link"}
                options={{
                  href: "https://scandiweb.com/adobe-magento-2-migration",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Migration"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-support",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Support"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/seo-services",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento SEO"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-upgrade-services",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Upgrade"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-commerce-developers",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Commerce Developers"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-commerce-developers",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Checkout Optimization"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                editable={true}
                options={{
                  href: "https://scandiweb.com/magento-pwa",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento PWA"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-performance-optimization",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Performance Optimisation"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "/magento-website-development",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Website development"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/services/ecommerce-design-services",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Design"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/services/aws-hosting-services-readymage",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento Hosting"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-react-development",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento front-end on React"}
                </Block>
              </Link>
              <Link
                block={"inline"}
                button={false}
                className={"default-link pr-10"}
                options={{
                  href: "https://scandiweb.com/magento-vue-js-development",
                }}
              >
                <Block className={"menu-link-text"} tag={"div"}>
                  {"Magento front-end on Vue.js"}
                </Block>
              </Link>
            </Grid>
          </Block>
        </Container>
        <HtmlEmbed
          className={"html-embed-14"}
          content={""}
          value={
            "%3Csvg%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%201440%2087%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M1316%2053.7649L1440%2086.4776L1440%200.000312813L1.51202e-05%20-2.28882e-05L1.76777e-05%2071.8864L40%2085.724L112%2071.8865L220.412%2085.724L319.264%2086.4776L419.916%2071.8864L524.2%2053.7648L618.144%2059.2754L718%2059.2754L821.066%2034.2971L919.357%2032.9726L1002%2059.2754L1114.3%2037.9243L1218%2037.9243L1316%2053.7649Z%22%20fill%3D%22%23EFF2F8%22%2F%3E%0A%3C%2Fsvg%3E"
          }
        />
      </Section>
    </div>
  );
}
