/**
 * @generated
 * @file XGallerSwiper (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link XGallerSwiper}
 */
export type XGallerSwiperProps = {
  footerSwiper?: boolean;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
  image6?: string;
};

/**
 * XGallerSwiper
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function XGallerSwiper({
  footerSwiper = false,
  image1 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773afc0e4c59e173e04654_container%20(1).webp",
  image2 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773b0f0be7c2b42973549e_container.webp",
  image3 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773b1fbde07fcc1271dd2a_container%20(2).webp",
  image4 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773b3646bbe14d7f1de160_container%20(3).webp",
  image5 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773b36c32f04a4e78272b3_container%20(4).webp",
  image6 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/69773b37f6b3e0e7c49ded29_Image%20Container.webp",
}: XGallerSwiperProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {footerSwiper ? (
        <Block className={"div-block-1828"} tag={"div"}>
          <Block className={"div-block-1824"} tag={"div"}>
            <Block
              className={"swiper-3 full-width abs footer-slider swiper"}
              tag={"div"}
            >
              <Block
                className={"swiper-wrapper-2 centered-wrapper swiper-wrapper"}
                tag={"div"}
              >
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4498"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image1}
                    width={"auto"}
                  />
                </Block>
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4500"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image2}
                    width={"auto"}
                  />
                </Block>
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4499"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image3}
                    width={"Auto"}
                  />
                </Block>
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4496"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image4}
                    width={"auto"}
                  />
                </Block>
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4497"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image5}
                    width={"auto"}
                  />
                </Block>
                <Block
                  className={"swiper-slide-2 footer-slider swiper-slide"}
                  tag={"div"}
                >
                  <Image
                    alt={""}
                    className={"image-4495"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image6}
                    width={"auto"}
                  />
                </Block>
              </Block>
            </Block>
            <HtmlEmbed
              className={"code-embed-130"}
              content={""}
              value={
                "%3Cscript%3E%0A%20%20window.addEventListener('load'%2C%20function%20()%20%7B%0A%20%20%20%20new%20Swiper('.footer-slider.swiper'%2C%20%7B%0A%20%20%20%20%20%20wrapperClass%3A%20'swiper-wrapper-2'%2C%0A%20%20%20%20%20%20slideClass%3A%20'swiper-slide-2'%2C%0A%0A%20%20%20%20%20%20slidesPerView%3A%20'auto'%2C%20%2F%2F%20show%20as%20many%20as%20fit%0A%20%20%20%20%20%20spaceBetween%3A%2020%2C%0A%0A%20%20%20%20%20%20loop%3A%20true%2C%20%2F%2F%20infinite%20loop%0A%20%20%20%20%20%20speed%3A%204000%2C%20%2F%2F%20controls%20smooth%20movement%20(higher%20%3D%20slower)%0A%0A%20%20%20%20%20%20autoplay%3A%20%7B%0A%20%20%20%20%20%20%20%20delay%3A%200%2C%20%2F%2F%20IMPORTANT%3A%20no%20delay%20%3D%20continuous%0A%20%20%20%20%20%20%20%20disableOnInteraction%3A%20false%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20reverseDirection%3A%20true%2C%0A%20%20%20%20%20%20%7D%2C%0A%0A%20%20%20%20%20%20allowTouchMove%3A%20true%2C%20%2F%2F%20optional%3A%20disables%20drag%20for%20pure%20ticker%20feel%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0A%3C%2Fscript%3E%0A%0A%3Cstyle%3E%0A%20%20%40media%20screen%20and%20(min-width%3A%202928px)%20%7B%0A%20%20%20%20.footer-slider.swiper%20.swiper-wrapper-2%20%7B%0A%20%20%20%20%20%20justify-content%3A%20center%20!important%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20.footer-slider.swiper%20.swiper-wrapper-2%20%7B%0A%20%20%20%20transition-timing-function%3A%20linear%20!important%3B%0A%20%20%7D%0A%3C%2Fstyle%3E"
              }
            />
          </Block>
        </Block>
      ) : null}
    </div>
  );
}
