/**
 * @generated
 * @file Articles3 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link Articles3}
 */
export type Articles3Props = {};

/**
 * Articles3
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function Articles3({}: Articles3Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"contribution-card"}
        id={"w-node-f5618016-e222-9810-1dee-097b5173f386-5173f386"}
        options={{
          href: "https://scandiweb.com/blog/the-time-for-migrating-to-magento-2-is-now/",
          target: "_blank",
        }}
      >
        <Block className={"div-block-224"} tag={"div"}>
          <Image
            alt={""}
            className={"blog-grid-image max-w-100"}
            height={"auto"}
            loading={"lazy"}
            src={
              "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/620f611a5464dec0e2bc64f7_Rectangle%201607%20(6)%20(1).avif"
            }
            width={"456"}
          />
          <Block className={"h3 mb-40 black h3-3-fixed"} tag={"div"}>
            {
              "Macron Sees 539% Increase in SERP Visibility After Content Optimization"
            }
          </Block>
        </Block>
        <Block className={"menu-link-text-2"} tag={"div"}>
          {"Read Blog Post"}
        </Block>
      </Link>
    </div>
  );
}
