/**
 * @generated
 * @file FooterDeprecated (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Container from "../webflow_modules/Layout/components/Container";
import Grid from "../webflow_modules/Layout/components/Grid";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";
import Section from "../webflow_modules/Layout/components/Section";
import Span from "../webflow_modules/Basic/components/Span";

/**
 * Props for {@link FooterDeprecated}
 */
export type FooterDeprecatedProps = {
  captionLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  captionText?: React.ReactNode;
  captionText2?: React.ReactNode;
  paragraph29Text?: React.ReactNode;
  unknownProp2024ScandiwebAllRightsReserved?: React.ReactNode;
};

/**
 * FooterDeprecated
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function FooterDeprecated({
  captionLink = {
    href: "/dedicated-ecommerce-teams",
  },

  captionText = "Adobe and Magento builds and migrations",
  captionText2 = "Dedicated eCommerce growth team",
  paragraph29Text = "© 2022 scandiweb. All Rights Reserved.",
  unknownProp2024ScandiwebAllRightsReserved = "© 2024 scandiweb. All Rights Reserved.",
}: FooterDeprecatedProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"footer"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Block className={"newsletter-background"} tag={"div"}>
          <Container className={"container py-64"} tag={"div"}>
            <Heading className={"h2 white newsletter"} tag={"h2"}>
              {"Tips, eBooks, and webinars"}
            </Heading>
            <Block className={"newsletter-wrapper"} tag={"div"}>
              <HtmlEmbed
                className={"html-embed-84"}
                content={""}
                value={
                  "%3Cscript%20charset%3D%22utf-8%22%20type%3D%22text%2Fjavascript%22%20src%3D%22%2F%2Fjs-eu1.hsforms.net%2Fforms%2Fembed%2Fv2.js%22%3E%3C%2Fscript%3E%0A%3Cscript%3E%0A%20%20hbspt.forms.create(%7B%0A%20%20%20%20region%3A%20%22eu1%22%2C%0A%20%20%20%20portalId%3A%20%2225724996%22%2C%0A%20%20%20%20formId%3A%20%223138576e-e2b3-4dac-8ff3-1039ab9428ba%22%0A%20%20%7D)%3B%0A%3C%2Fscript%3E"
                }
              />
            </Block>
          </Container>
        </Block>
        <Block className={"div-block-63"} tag={"div"}>
          <Block className={"unicorn-gradient-bg"} tag={"div"} />
          <Container className={"content-container relative top"} tag={"div"}>
            <Block className={"upper-block rainbow"} tag={"div"}>
              <Grid className={"sitemap-grid rainbow"} tag={"div"}>
                <Block className={"sitemap-cell"} tag={"div"}>
                  <Block
                    className={"default-text footer white big mb-8"}
                    tag={"div"}
                  >
                    {"Technology"}
                  </Block>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/adobe-commerce-magento",
                    }}
                  >
                    {captionText}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-_0efeebcf-f028-cf0d-1624-7113f40cdcc4-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/b2b-ecommerce-solutions",
                    }}
                  >
                    {"B2B eCommerce solutions"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-fa44d81a-4966-af0f-4580-cb214d276d3e-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/custom-ecommerce-development-middleware",
                    }}
                  >
                    {"Custom builds and middleware"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-_9c22caf5-7136-e9b9-3d3f-9c87bfdf32bd-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/services/bigcommerce-development-services",
                    }}
                  >
                    {"BigCommerce Development Services"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/hyva-themes",
                    }}
                  >
                    {"Hyvä Themes"}
                  </Link>
                  <Paragraph
                    className={"paragraph-27"}
                    id={"w-node-d1eee9db-bc37-d56e-0ab2-4af39b1508bb-2192e9af"}
                  >
                    <Link
                      block={""}
                      button={false}
                      options={{
                        href: "#",
                      }}
                    >
                      <Span className={"caption footer"}>{"Headless"}</Span>
                    </Link>
                    <Span className={"caption footer"}> </Span>
                    {"& "}
                    <Link
                      block={""}
                      button={false}
                      className={"caption footer"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"PWA eCommerce"}
                    </Link>
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/microservices-development",
                    }}
                  >
                    {"Microservices for eCommerce"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-a13d2d98-511e-dd17-278a-2eaf3f777a36-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/front-end-ecommerce-js",
                    }}
                  >
                    {"Modern JS development"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-_35f371af-3c4a-dcd6-8c16-e9079be7cea5-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/services/aws-hosting-services-readymage",
                    }}
                  >
                    {"Magento hosting"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/scandipwa",
                    }}
                  >
                    {"ScandiPWA"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/bigcommerce-development-services",
                    }}
                  >
                    {"BigCommerce development services"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/commercetools-development-support",
                    }}
                  >
                    {"Commercetools development & support"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/pimcore-support",
                    }}
                  >
                    {"Pimcore support"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/salesforce-commerce-cloud",
                    }}
                  >
                    {"Salesforce Commerce Cloud"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/sanity-development-support",
                    }}
                  >
                    {"Sanity development & support"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/sap-commerce-cloud",
                    }}
                  >
                    {"SAP Commerce Cloud"}
                  </Link>
                </Block>
                <Block className={"sitemap-cell"} tag={"div"}>
                  <Block
                    className={"default-text footer white big mb-8"}
                    tag={"div"}
                  >
                    {"eCommerce strategy"}
                  </Block>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/partners",
                    }}
                  >
                    {"Partnerships"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/strategic-roadmap-ecommerce",
                    }}
                  >
                    {"Strategic eCommerce roadmap"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={captionLink}
                  >
                    {captionText2}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/project-management-ecommerce",
                    }}
                  >
                    {"Project and delivery management"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/ecommerce-support-services",
                    }}
                  >
                    {"Long-term support and modernization"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/ecommerce-qa-automation",
                    }}
                  >
                    {"Quality assurance and QA automation"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/pim-ecommerce-integration",
                    }}
                  >
                    {"PIM integration and support"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/gdpr-compliance-services",
                    }}
                  >
                    {"eCommerce legal advice, GDPR, CCPA"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "/scandiblox-metaverse-ecommerce",
                    }}
                  >
                    {"ScandiBlox - Metaverse on Roblox"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/ai-content-strategy-for-ecommerce",
                    }}
                  >
                    {"AI for content"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://www.scandiweb.ai/",
                    }}
                  >
                    {"AI services for business"}
                  </Link>
                </Block>
                <Block className={"sitemap-cell"} tag={"div"}>
                  <Block
                    className={"default-text footer white big mb-8"}
                    tag={"div"}
                  >
                    {"Acquisition & Retention"}
                  </Block>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/email-marketing-services",
                    }}
                  >
                    {"eCommerce email marketing"}
                  </Link>
                  <Paragraph
                    className={"paragraph-27"}
                    id={"w-node-e6b9bacd-659f-2e64-f0bd-e7f4068c51f0-2192e9af"}
                  >
                    <Link
                      block={""}
                      button={false}
                      options={{
                        href: "#",
                      }}
                    >
                      <Span className={"caption footer"}>{"Paid social"}</Span>
                    </Link>
                    <Span className={"caption footer"}> </Span>
                    {"& "}
                    <Link
                      block={""}
                      button={false}
                      className={"caption footer"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"search ads management"}
                    </Link>
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/seo-services",
                    }}
                  >
                    {"SEO and content"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/tiktok-shop",
                    }}
                  >
                    {"TikTok Shop management"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-_1b6dfa67-3ded-c4cf-a96a-af2c89930808-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/services/tiktok-ads-management-services",
                    }}
                  >
                    {"TikTok Ads management"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-_1952443b-9793-c407-8860-422fc7a08dfc-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/traffic-acquisition",
                    }}
                  >
                    {"Traffic acquisition"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    id={"w-node-fda83759-a2d4-4ad3-7601-59663a3f8dc8-2192e9af"}
                    options={{
                      href: "https://scandiweb.com/services/product-feed-management",
                    }}
                  >
                    {"Product feed management"}
                  </Link>
                </Block>
                <Block className={"sitemap-cell"} tag={"div"}>
                  <Block
                    className={"default-text footer white big mb-8"}
                    tag={"div"}
                  >
                    {"CX & Data analytics"}
                  </Block>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/cx-customer-experience-optimization",
                    }}
                  >
                    {"Customer experience optimization"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/cro-ux",
                    }}
                  >
                    {"UX/UI optimization and CRO"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/ecommerce-design-services",
                    }}
                  >
                    {"Design & creative"}
                  </Link>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/scandilytics",
                    }}
                  >
                    {"Actionable data analytics"}
                  </Link>
                  <Paragraph
                    className={"paragraph-27"}
                    id={"w-node-_557f3e6c-4261-777c-309f-ca19c144eaa2-2192e9af"}
                  >
                    <Link
                      block={""}
                      button={false}
                      options={{
                        href: "#",
                      }}
                    >
                      <Span className={"caption footer"}>{"GA4"}</Span>
                    </Link>
                    <Span className={"caption footer"}> </Span>
                    {"& "}
                    <Link
                      block={""}
                      button={false}
                      className={"caption footer"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Adobe Analytics support"}
                    </Link>
                  </Paragraph>
                  <Link
                    block={""}
                    button={false}
                    className={"caption footer"}
                    options={{
                      href: "https://scandiweb.com/services/website-localization-services",
                    }}
                  >
                    {"Website localization services"}
                  </Link>
                </Block>
              </Grid>
            </Block>
            <Image
              alt={""}
              className={"image-3494"}
              height={"auto"}
              loading={"lazy"}
              src={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/627bf5e3317127574d6f7006_345.svg"
              }
              width={"auto"}
            />
            <Block className={"div-block-335"} tag={"div"}>
              <Image
                alt={""}
                className={"image-3914"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/6295f5acd05aa2526fba9859_unicorn.svg"
                }
                width={"auto"}
              />
              <Block className={"div-block-334"} tag={"div"}>
                <Paragraph className={"paragraph-31"}>
                  {"I am Rainbow, I take pickles and make them into diamonds"}
                </Paragraph>
              </Block>
              <Image
                alt={""}
                className={"image-3611"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/629600fffedb7b0e5cefcf55_stars.svg"
                }
                width={"auto"}
              />
            </Block>
            <Block className={"lower-block bp-427-flex-vertical"} tag={"div"}>
              <Block className={"privacyfooter"} tag={"div"}>
                <Link
                  block={""}
                  button={false}
                  className={"caption footer pad10 a50"}
                  options={{
                    href: "/terms-of-service",
                  }}
                >
                  {"Terms of Service"}
                </Link>
                <Link
                  block={""}
                  button={false}
                  className={"caption footer pad10 a50"}
                  options={{
                    href: "/privacy-policy",
                  }}
                >
                  {" Privacy Policy"}
                </Link>
                <Link
                  block={""}
                  button={false}
                  className={"caption footer pad10 a50"}
                  id={"w-node-_0efeebcf-f028-cf0d-1624-7113f40cdcf2-2192e9af"}
                  options={{
                    href: "/cookie-policy",
                  }}
                >
                  {"Manage Cookies"}
                </Link>
                <Link
                  block={""}
                  button={false}
                  className={"caption footer pad10 a50"}
                  options={{
                    href: "https://scandiweb.com/services/magento-demo",
                  }}
                >
                  {"Magento 2 Demo Store"}
                </Link>
              </Block>
              <Block className={"scoial-footer"} tag={"div"}>
                <Link
                  block={"inline"}
                  button={false}
                  options={{
                    href: "https://www.linkedin.com/company/scandiweb",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M15.335%2015.339H12.67v-4.177c0-.996-.02-2.278-1.39-2.278-1.389%200-1.601%201.084-1.601%202.205v4.25H7.013V6.75h2.56v1.17h.035c.358-.674%201.228-1.387%202.528-1.387%202.7%200%203.2%201.778%203.2%204.091v4.715ZM4.003%205.575a1.546%201.546%200%200%201-1.548-1.549%201.548%201.548%200%201%201%201.547%201.549Zm1.336%209.764H2.666V6.75H5.34v8.589ZM16.67%200H1.329C.593%200%200%20.58%200%201.297v15.406C0%2017.42.594%2018%201.328%2018h15.338C17.4%2018%2018%2017.42%2018%2016.703V1.297C18%20.58%2017.4%200%2016.666%200h.003Z%22%20fill%3D%22currentColor%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  options={{
                    href: "https://www.facebook.com/scandiweb",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M18%209.055C18%204.055%2013.97%200%209%200S0%204.054%200%209.055c0%204.52%203.291%208.265%207.594%208.944v-6.327H5.309V9.054h2.285V7.06c0-2.269%201.344-3.523%203.4-3.523.983%200%202.014.178%202.014.178v2.228h-1.135c-1.119%200-1.467.698-1.467%201.414v1.698H12.9l-.399%202.618h-2.097V18C14.71%2017.32%2018%2013.574%2018%209.055Z%22%20fill%3D%22currentColor%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  options={{
                    href: "https://www.youtube.com/c/Scandiwebcom",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2217%22%20height%3D%2212%22%20viewBox%3D%220%200%2017%2012%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M16.6444%201.87416C16.5484%201.51173%2016.359%201.18094%2016.0952%200.914912C15.8314%200.648887%2015.5025%200.456966%2015.1413%200.358368C13.816%208.45956e-08%208.5%200%208.5%200C8.5%200%203.18396%208.45956e-08%201.85796%200.358368C1.497%200.45714%201.16825%200.649131%200.904597%200.915138C0.640943%201.18115%200.451627%201.51184%200.355583%201.87416C0%203.21112%200%206%200%206C0%206%200%208.78888%200.355583%2010.1258C0.451623%2010.4883%200.641024%2010.8191%200.904819%2011.0851C1.16861%2011.3511%201.49754%2011.543%201.85867%2011.6416C3.18396%2012%208.5%2012%208.5%2012C8.5%2012%2013.816%2012%2015.142%2011.6416C15.5032%2011.5431%2015.8322%2011.3512%2016.096%2011.0852C16.3598%2010.8191%2016.5492%2010.4883%2016.6451%2010.1258C17%208.78888%2017%206%2017%206C17%206%2017%203.21112%2016.6444%201.87416ZM6.76104%208.53199V3.46801L11.2044%206L6.76104%208.53199Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                    }
                  />
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  options={{
                    href: "https://www.instagram.com/scandiweb/",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2218%22%20height%3D%2218%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M9%200C6.555%200%206.25.011%205.29.054%204.33.099%203.679.25%203.105.472A4.407%204.407%200%200%200%201.51%201.51c-.5.5-.809%201.003-1.038%201.595C.25%203.679.098%204.331.054%205.29.009%206.25%200%206.555%200%209c0%202.445.011%202.75.054%203.71.045.958.196%201.611.418%202.185.23.591.538%201.094%201.038%201.595.5.499%201.003.809%201.595%201.038.575.222%201.227.374%202.185.418.96.045%201.265.054%203.71.054%202.445%200%202.75-.011%203.71-.054.958-.045%201.611-.197%202.185-.419a4.423%204.423%200%200%200%201.595-1.038c.499-.5.809-1%201.038-1.594.222-.574.374-1.227.418-2.185.045-.96.054-1.265.054-3.71%200-2.445-.011-2.75-.054-3.71-.045-.958-.197-1.612-.419-2.185A4.417%204.417%200%200%200%2016.49%201.51c-.5-.5-1-.809-1.594-1.038C14.321.25%2013.668.098%2012.71.054%2011.75.009%2011.445%200%209%200Zm0%201.62c2.402%200%202.689.012%203.637.053.878.041%201.354.187%201.67.311.422.163.72.358%201.037.672.315.315.51.615.672%201.036.123.317.27.793.31%201.67.043.95.052%201.235.052%203.638%200%202.403-.01%202.689-.055%203.637-.046.878-.192%201.354-.316%201.67-.168.422-.359.72-.674%201.037-.314.315-.618.51-1.035.672-.315.123-.799.27-1.676.31-.956.043-1.237.052-3.645.052s-2.689-.01-3.644-.055c-.878-.046-1.362-.192-1.677-.316a2.787%202.787%200%200%201-1.034-.674%202.732%202.732%200%200%201-.675-1.035c-.124-.315-.27-.799-.315-1.676-.034-.945-.046-1.237-.046-3.633%200-2.397.012-2.69.046-3.646.046-.878.191-1.36.315-1.675.157-.428.36-.72.675-1.036a2.662%202.662%200%200%201%201.034-.674c.315-.124.788-.27%201.666-.315.956-.034%201.237-.046%203.644-.046L9%201.62Zm0%202.758a4.621%204.621%200%201%200%200%209.243%204.621%204.621%200%200%200%200-9.243ZM9%2012a3%203%200%201%201%200-6%203%203%200%201%201%200%206Zm5.884-7.804a1.08%201.08%200%200%201-2.16%200%201.08%201.08%200%200%201%202.16%200Z%22%20fill%3D%22currentColor%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"link-block-12"}
                  options={{
                    href: "https://twitter.com/scandiweb?lang=en",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2218%22%20height%3D%2214%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M17.965%201.668a7.764%207.764%200%200%201-2.119.556A3.59%203.59%200%200%200%2017.468.27a7.836%207.836%200%200%201-2.345.85A3.743%203.743%200%200%200%2013.03.046a3.835%203.835%200%200%200-2.342.37%203.6%203.6%200%200%200-1.622%201.658%203.392%203.392%200%200%200-.231%202.261C5.767%204.198%203.05%202.787%201.23.657a3.347%203.347%200%200%200-.5%201.776c0%201.228.653%202.306%201.642%202.94A3.805%203.805%200%200%201%20.7%204.931v.043c0%20.816.294%201.606.833%202.238A3.724%203.724%200%200%200%203.66%208.438a3.91%203.91%200%200%201-1.659.061%203.552%203.552%200%200%200%201.316%201.756c.62.44%201.366.683%202.137.697a7.616%207.616%200%200%201-4.576%201.51c-.293%200-.585-.016-.878-.047A10.844%2010.844%200%200%200%205.668%2014c6.79%200%2010.498-5.38%2010.498-10.037%200-.15%200-.302-.011-.452A7.283%207.283%200%200%200%2018%201.682l-.035-.014Z%22%20fill%3D%22currentColor%22%2F%3E%3C%2Fsvg%3E"
                    }
                  />
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  options={{
                    href: "https://www.tiktok.com/@scandiweb",
                    target: "_blank",
                  }}
                >
                  <HtmlEmbed
                    className={"html-embed-27"}
                    content={""}
                    value={
                      "%3Csvg%20width%3D%2214%22%20height%3D%2216%22%20viewBox%3D%220%200%2014%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M7.35281%200.0133332C8.23238%200%209.10525%200.00666658%209.97811%200C10.0318%201.01999%2010.4011%202.05997%2011.1531%202.77997C11.9051%203.51996%2012.966%203.85995%2014%203.97328V6.65992C13.0331%206.62658%2012.0596%206.42659%2011.18%206.01326C10.7973%205.83993%2010.4414%205.61993%2010.0923%205.39327C10.0855%207.33991%2010.099%209.28655%2010.0788%2011.2265C10.0251%2012.1598%209.71625%2013.0865%209.17239%2013.8532C8.29281%2015.1331%206.76866%2015.9665%205.20422%2015.9931C4.24407%2016.0465%203.28392%2015.7865%202.46477%2015.3065C1.10847%2014.5132%200.155035%2013.0598%200.0140341%2011.4999C0.000605427%2011.1665%20-0.0061089%2010.8332%200.00731977%2010.5065C0.128178%209.23988%200.759326%208.02657%201.73962%207.19991C2.8542%206.23992%204.41193%205.77993%205.86894%206.05326C5.88237%207.03991%205.84208%208.02657%205.84208%209.01322C5.17736%208.79989%204.3985%208.85989%203.81435%209.25988C3.39135%209.53321%203.06906%209.95321%202.9012%2010.4265C2.7602%2010.7665%202.80048%2011.1399%202.8072%2011.4999C2.96834%2012.5932%204.02921%2013.5132%205.15722%2013.4132C5.90922%2013.4065%206.62766%2012.9732%207.01709%2012.3398C7.14466%2012.1198%207.28566%2011.8932%207.29238%2011.6332C7.35952%2010.4399%207.33266%209.25322%207.33938%208.0599C7.34609%205.37327%207.33266%202.6933%207.35281%200.0133332V0.0133332Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                    }
                  />
                </Link>
              </Block>
              <Paragraph className={"paragraph-29"}>
                {unknownProp2024ScandiwebAllRightsReserved}
              </Paragraph>
            </Block>
          </Container>
        </Block>
      </Section>
    </div>
  );
}
