/**
 * @generated
 * @file H2WhiteGreen (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Heading from "../webflow_modules/Basic/components/Heading";

/**
 * Props for {@link H2WhiteGreen}
 */
export type H2WhiteGreenProps = {
  title?: React.ReactNode;
};

/**
 * H2WhiteGreen
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function H2WhiteGreen({
  title = (
    <>
      {"Why "}
      {" love working with scandiweb"}
    </>
  ),
}: H2WhiteGreenProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Heading className={"h2-white-v7"} tag={"h2"}>
        {title}
      </Heading>
    </div>
  );
}
