/**
 * @generated
 * @file VideoArticle (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Link from "../webflow_modules/Basic/components/Link";
import YouTubeVideo from "../webflow_modules/Embed/components/YouTubeVideo";

/**
 * Props for {@link VideoArticle}
 */
export type VideoArticleProps = {};

/**
 * VideoArticle
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function VideoArticle({}: VideoArticleProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"contribution-card"}
        id={"w-node-_20fd7dcf-58ad-5a13-994b-a62f7808994b-7808994b"}
        options={{
          href: "https://scandiweb.com/blog/webinar-marello-and-magento/",
          target: "_blank",
        }}
      >
        <Block className={"div-block-224"} tag={"div"}>
          <YouTubeVideo
            aspectRatio={0.5617021276595745}
            autoplay={true}
            className={"youtube-2"}
            controls={false}
            muted={true}
            privacyMode={false}
            showAllRelatedVideos={false}
            startAt={0}
            title={
              "Marello + Magento: Unified eCommerce enabling full backend process automation"
            }
            videoId={"naMOtclpc6w"}
          />
          <Block className={"h3 mb-40 black"} tag={"div"}>
            {"Marello + Magento"}
          </Block>
        </Block>
        <Block className={"menu-link-text-2"} tag={"div"}>
          {"Watch Free Webinar"}
        </Block>
      </Link>
    </div>
  );
}
