/**
 * @generated
 * @file ViiewlAll (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link ViiewlAll}
 */
export type ViiewlAllProps = {};

/**
 * ViiewlAll
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function ViiewlAll({}: ViiewlAllProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"nav-block sticky mb-72"} tag={"div"}>
        <Link
          block={"inline"}
          button={false}
          options={{
            href: "#",
          }}
        >
          <HtmlEmbed
            className={"viewall"}
            content={""}
            value={
              "%3Csvg%20width%3D%2294%22%20height%3D%2224%22%20viewBox%3D%220%200%2094%2024%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M14%2017.0834L9%2012.0834L14%207.08337%22%20stroke%3D%22currentColor%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%0A%3Cpath%20d%3D%22M30.3891%207.77273L32.4985%2014.4034H32.5795L34.6931%207.77273H36.7386L33.73%2016.5H31.3522L28.3394%207.77273H30.3891ZM40.8342%207.77273V16.5H38.989V7.77273H40.8342ZM43.5523%2016.5V7.77273H49.433V9.29403H45.3974V11.3736H49.1304V12.8949H45.3974V14.9787H49.45V16.5H43.5523ZM54.0644%2016.5L51.5673%207.77273H53.5829L55.0275%2013.8366H55.0999L56.6937%207.77273H58.4195L60.009%2013.8494H60.0857L61.5303%207.77273H63.546L61.0488%2016.5H59.2505L57.5886%2010.794H57.5204L55.8627%2016.5H54.0644ZM71.2151%2016.5H69.2379L72.2506%207.77273H74.6285L77.637%2016.5H75.6597L73.4737%209.76705H73.4055L71.2151%2016.5ZM71.0915%2013.0696H75.762V14.5099H71.0915V13.0696ZM79.8874%2016.5V7.77273H81.7326V14.9787H85.4741V16.5H79.8874ZM87.896%2016.5V7.77273H89.7412V14.9787H93.4827V16.5H87.896Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
            }
          />
        </Link>
      </Block>
    </div>
  );
}
