/**
 * @generated
 * @file XDropdownBlocks (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import BackgroundVideoWrapper from "../webflow_modules/BackgroundVideo/components/BackgroundVideoWrapper";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Image from "../webflow_modules/Basic/components/Image";
import Link from "../webflow_modules/Basic/components/Link";
import { DropdownBlock } from "../DropdownBlock";

/**
 * Props for {@link XDropdownBlocks}
 */
export type XDropdownBlocksProps = {
  dropdownBlockImage1?: string;
  dropdownBlockImage2?: string;
  dropdownBlockLink1?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  dropdownBlockLink2?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  dropdownBlockLink3?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  dropdownBlockLink4?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  dropdownBlockTitle?: React.ReactNode;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
  image6?: string;
  image7?: string;
  image8?: string;
  title1?: React.ReactNode;
  title2?: React.ReactNode;
  title3?: React.ReactNode;
  title4?: React.ReactNode;
};

/**
 * XDropdownBlocks
 *
 * @see {@link https://scandiweb.design.webflow.com | Source site in Webflow}
 */
export function XDropdownBlocks({
  dropdownBlockImage1 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addabe66d1ca9a3433c140_Alfreds-Genkins.avif",
  dropdownBlockImage2 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addabef1952d14d8384e94_Kaspars-Kalkis.avif",

  dropdownBlockLink1 = {
    href: "/contact",
  },

  dropdownBlockLink2 = {
    href: "https://scandiweb.com/services",
    target: "_blank",
  },

  dropdownBlockLink3 = {
    href: "/contact",
  },

  dropdownBlockLink4 = {
    href: "https://scandiweb.com/services",
    target: "_blank",
  },

  dropdownBlockTitle = "Tech & development",
  image1 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67adcdffc65af9f54f9588f6_Maris%20Skujins.avif",
  image2 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67adcdff37506f0bc7782b04_Aigars%20Pavlovics.avif",
  image3 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb44ef7f0774208a1d82_Glebs-Vrevskis.avif",
  image4 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb442e095471af215732_Olga-Kimalana.avif",
  image5 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb88e98472f24e70d19c_Ahmed-Ashraf.avif",
  image6 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb8809bb0e0656307fed_Lina-Ivanova.avif",
  image7 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb888a13cbe81e03e23a_Reinis-Groskops.avif",
  image8 = "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21/67addb889df939f040a93a26_Deniss-Rostovskis.avif",
  title1 = "Strategy & consulting ",
  title2 = "Customer experience",
  title3 = "Growth marketing",
  title4 = "Data & analytics",
}: XDropdownBlocksProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"dropdown_blocks"} tag={"div"}>
        <Block className={"dropdown_block"} tag={"div"}>
          <Block
            className={"dropdown_content  open"}
            id={"dropdown-buttom"}
            tag={"div"}
          >
            <BackgroundVideoWrapper
              autoPlay={true}
              className={"accordeon-background-video"}
              loop={true}
              posterImage={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-poster-00001.jpg"
              }
              sources={[
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.webm",
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.mp4",
              ]}
              tag={"div"}
            />
            <Block className={"div-block-1371"} tag={"div"}>
              <Heading className={"h3_text"} tag={"h3"}>
                {title1}
              </Heading>
              <Block className={"link_texts"} tag={"div"}>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Digital transformation"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Market expansion"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"AI adoptation"}
                </Block>
                <Block className={"text-block-257  no-stroke"} tag={"div"}>
                  {"B2C & B2B"}
                </Block>
              </Block>
              <Block className={"cta-buttons hide-on-mobile"} tag={"div"}>
                <Link
                  block={""}
                  button={true}
                  className={"cta_white"}
                  options={{
                    href: "/contact",
                  }}
                >
                  {"Book a consultation"}
                </Link>
                <Link
                  block={""}
                  button={true}
                  className={"cta_transparent"}
                  options={{
                    href: "https://scandiweb.com/services",
                    target: "_blank",
                  }}
                >
                  {"All services"}
                </Link>
              </Block>
            </Block>
            <Block className={"text_persons"} tag={"div"}>
              <Block className={"dropdown-text-block"} tag={"div"}>
                {
                  "scandiweb partners with leadership teams to set priorities, create actionable roadmaps, and tackle key challenges like market expansion, technology future-proofing, and scaling during rapid growth."
                }
              </Block>
              <Block className={"person_block"} tag={"div"}>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image1}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Maris Skujins"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Head of BA & Strategy"}
                    </Block>
                  </Block>
                </Block>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image2}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Aigars Pavlovics"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Executive board"}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
            <Block className={"cta-buttons hide-on-desktop"} tag={"div"}>
              <Link
                block={""}
                button={true}
                className={"cta_white"}
                options={{
                  href: "/contact",
                }}
              >
                {"Book a consultation"}
              </Link>
              <Link
                block={""}
                button={true}
                className={"cta_transparent"}
                options={{
                  href: "https://scandiweb.com/services",
                  target: "_blank",
                }}
              >
                {"All services"}
              </Link>
            </Block>
            <HtmlEmbed
              className={"drop-open"}
              content={""}
              id={"drop-open"}
              value={
                "%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2020%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M7.38818%2019H12.6117V12.6118H19V7.38831H12.6117V1H7.38818L7.38818%207.38831H1V12.6118H7.38818L7.38818%2019Z%22%20fill%3D%22%23F8F4EF%22%2F%3E%0A%3C%2Fsvg%3E"
              }
            />
          </Block>
        </Block>
        <DropdownBlock
          image1={dropdownBlockImage1}
          image2={dropdownBlockImage2}
          link1={dropdownBlockLink1}
          link2={dropdownBlockLink2}
          link3={dropdownBlockLink3}
          link4={dropdownBlockLink4}
          title={dropdownBlockTitle}
        />
        <Block className={"dropdown_block"} tag={"div"}>
          <Block className={"dropdown_content "} tag={"div"}>
            <BackgroundVideoWrapper
              autoPlay={true}
              className={"accordeon-background-video"}
              loop={true}
              posterImage={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-poster-00001.jpg"
              }
              sources={[
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.webm",
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.mp4",
              ]}
              tag={"div"}
            />
            <Block className={"div-block-1371"} tag={"div"}>
              <Heading className={"h3_text"} tag={"h3"}>
                {title2}
              </Heading>
              <Block className={"link_texts"} tag={"div"}>
                <Block className={"text-block-257"} tag={"div"}>
                  {"UI/UX design"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Conversion rate optimization"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Personalization"}
                </Block>
                <Block className={"text-block-257  no-stroke"} tag={"div"}>
                  {"Loyalty programs"}
                </Block>
              </Block>
              <Block className={"cta-buttons hide-on-mobile"} tag={"div"}>
                <Link
                  block={""}
                  button={true}
                  className={"cta_white"}
                  options={{
                    href: "/contact",
                  }}
                >
                  {"Book a consultation"}
                </Link>
                <Link
                  block={""}
                  button={true}
                  className={"cta_transparent"}
                  options={{
                    href: "https://scandiweb.com/services",
                    target: "_blank",
                  }}
                >
                  {"All services"}
                </Link>
              </Block>
            </Block>
            <Block className={"text_persons"} tag={"div"}>
              <Block className={"dropdown-text-block"} tag={"div"}>
                {
                  "Every touchpoint is optimized for clarity and speed—clean UX design, seamless navigation, and fast load times convert visitors, while personalization and mobile-first solutions build loyalty."
                }
              </Block>
              <Block className={"person_block"} tag={"div"}>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image3}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Glebs Vrevskis"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Executive board"}
                    </Block>
                  </Block>
                </Block>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image4}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Olga Kimalana"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Head of Digital Experience"}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
            <Block className={"cta-buttons hide-on-desktop"} tag={"div"}>
              <Link
                block={""}
                button={true}
                className={"cta_white"}
                options={{
                  href: "/contact",
                }}
              >
                {"Book a consultation"}
              </Link>
              <Link
                block={""}
                button={true}
                className={"cta_transparent"}
                options={{
                  href: "https://scandiweb.com/services",
                  target: "_blank",
                }}
              >
                {"All services"}
              </Link>
            </Block>
            <HtmlEmbed
              className={"drop-open"}
              content={""}
              id={"drop-open"}
              value={
                "%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2020%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M7.38818%2019H12.6117V12.6118H19V7.38831H12.6117V1H7.38818L7.38818%207.38831H1V12.6118H7.38818L7.38818%2019Z%22%20fill%3D%22%23F8F4EF%22%2F%3E%0A%3C%2Fsvg%3E"
              }
            />
          </Block>
        </Block>
        <Block className={"dropdown_block"} tag={"div"}>
          <Block className={"dropdown_content "} tag={"div"}>
            <BackgroundVideoWrapper
              autoPlay={true}
              className={"accordeon-background-video"}
              loop={true}
              posterImage={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-poster-00001.jpg"
              }
              sources={[
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.webm",
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.mp4",
              ]}
              tag={"div"}
            />
            <Block className={"div-block-1371"} tag={"div"}>
              <Heading className={"h3_text"} tag={"h3"}>
                {title3}
              </Heading>
              <Block className={"link_texts"} tag={"div"}>
                <Block className={"text-block-257"} tag={"div"}>
                  {"SEO"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Paid media"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Lifecycle marketing"}
                </Block>
                <Block className={"text-block-257  no-stroke"} tag={"div"}>
                  {"Localization"}
                </Block>
              </Block>
              <Block className={"cta-buttons hide-on-mobile"} tag={"div"}>
                <Link
                  block={""}
                  button={true}
                  className={"cta_white"}
                  options={{
                    href: "/contact",
                  }}
                >
                  {"Book a consultation"}
                </Link>
                <Link
                  block={""}
                  button={true}
                  className={"cta_transparent"}
                  options={{
                    href: "https://scandiweb.com/services",
                    target: "_blank",
                  }}
                >
                  {"All services"}
                </Link>
              </Block>
            </Block>
            <Block className={"text_persons"} tag={"div"}>
              <Block className={"dropdown-text-block"} tag={"div"}>
                {
                  "SEO, paid campaigns, and omnichannel strategies drive traffic, while email, SMS, and loyalty programs boost conversions and repeat purchases, all backed by data for lasting growth."
                }
              </Block>
              <Block className={"person_block"} tag={"div"}>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image5}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Ahmed Ashraf"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Head of Paid Media"}
                    </Block>
                  </Block>
                </Block>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image6}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Lina Ivanova"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Head of Traffic Acquisition"}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
            <Block className={"cta-buttons hide-on-desktop"} tag={"div"}>
              <Link
                block={""}
                button={true}
                className={"cta_white"}
                options={{
                  href: "/contact",
                }}
              >
                {"Book a consultation"}
              </Link>
              <Link
                block={""}
                button={true}
                className={"cta_transparent"}
                options={{
                  href: "https://scandiweb.com/services",
                  target: "_blank",
                }}
              >
                {"All services"}
              </Link>
            </Block>
            <HtmlEmbed
              className={"drop-open"}
              content={""}
              id={"drop-open"}
              value={
                "%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2020%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M7.38818%2019H12.6117V12.6118H19V7.38831H12.6117V1H7.38818L7.38818%207.38831H1V12.6118H7.38818L7.38818%2019Z%22%20fill%3D%22%23F8F4EF%22%2F%3E%0A%3C%2Fsvg%3E"
              }
            />
          </Block>
        </Block>
        <Block className={"dropdown_block"} tag={"div"}>
          <Block className={"dropdown_content "} tag={"div"}>
            <BackgroundVideoWrapper
              autoPlay={true}
              className={"accordeon-background-video"}
              loop={true}
              posterImage={
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-poster-00001.jpg"
              }
              sources={[
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.webm",
                "https://cdn.prod.website-files.com/61387043ab1e4143deac1e21%2F67b330208ae7bcd94a05f3a2_accordeon-video_1-transcode.mp4",
              ]}
              tag={"div"}
            />
            <Block className={"div-block-1371"} tag={"div"}>
              <Heading className={"h3_text"} tag={"h3"}>
                {title4}
              </Heading>
              <Block className={"link_texts"} tag={"div"}>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Data management"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Customer behaviour"}
                </Block>
                <Block className={"text-block-257"} tag={"div"}>
                  {"Compliance"}
                </Block>
                <Block className={"text-block-257  no-stroke"} tag={"div"}>
                  {"Customer data platform"}
                </Block>
              </Block>
              <Block className={"cta-buttons hide-on-mobile"} tag={"div"}>
                <Link
                  block={""}
                  button={true}
                  className={"cta_white"}
                  options={{
                    href: "/contact",
                  }}
                >
                  {"Book a consultation"}
                </Link>
                <Link
                  block={""}
                  button={true}
                  className={"cta_transparent"}
                  options={{
                    href: "https://scandiweb.com/services",
                    target: "_blank",
                  }}
                >
                  {"All services"}
                </Link>
              </Block>
            </Block>
            <Block className={"text_persons"} tag={"div"}>
              <Block className={"dropdown-text-block"} tag={"div"}>
                {
                  "Advanced tracking, connected CDPs, and detailed analytics provide clear visibility into performance and customer behavior, helping leadership teams make smarter, faster decisions to improve efficiency, increase conversions, and drive growth."
                }
              </Block>
              <Block className={"person_block"} tag={"div"}>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image7}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Reinis Groskops"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"Head of Data & Analytics"}
                    </Block>
                  </Block>
                </Block>
                <Block className={"dropdown-person-item"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"image-4286"}
                    height={"auto"}
                    loading={"eager"}
                    src={image8}
                    width={"56"}
                  />
                  <Block className={"div-block-1373"} tag={"div"}>
                    <Block className={"text-block-259"} tag={"div"}>
                      {"Deniss Rostovskis"}
                    </Block>
                    <Block className={"caption_text"} tag={"div"}>
                      {"CIO"}
                    </Block>
                  </Block>
                </Block>
              </Block>
            </Block>
            <Block className={"cta-buttons hide-on-desktop"} tag={"div"}>
              <Link
                block={""}
                button={true}
                className={"cta_white"}
                options={{
                  href: "/contact",
                }}
              >
                {"Book a consultation"}
              </Link>
              <Link
                block={""}
                button={true}
                className={"cta_transparent"}
                options={{
                  href: "https://scandiweb.com/services",
                  target: "_blank",
                }}
              >
                {"All services"}
              </Link>
            </Block>
            <HtmlEmbed
              className={"drop-open"}
              content={""}
              id={"drop-open"}
              value={
                "%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2020%2020%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M7.38818%2019H12.6117V12.6118H19V7.38831H12.6117V1H7.38818L7.38818%207.38831H1V12.6118H7.38818L7.38818%2019Z%22%20fill%3D%22%23F8F4EF%22%2F%3E%0A%3C%2Fsvg%3E"
              }
            />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
